'use strict';
let experienceHistory=[],readinessData=null,choiceData=[],readinessRun=0,whatsNewShown='';
const helpLinks=document.createElement('div');helpLinks.className='release-links';helpLinks.innerHTML='<button id="whats-new">What’s new <span id="whats-new-dot" hidden>●</span></button><button id="send-feedback">Send feedback</button>';document.querySelector('.sidebar footer').before(helpLinks);
async function loadHistory(){experienceHistory=await api('/api/installation-history');return experienceHistory;}
function historyDialog(){showDialog(dialogHeader('Installation history')+`<p>Installs made with this release appear here. Tell us whether a skill helped after you try it. Undo checks for edits and keeps an archived copy.</p><div class="history-list">${experienceHistory.map((r,i)=>`<article class="history-entry"><div><h3>${esc(displaySkillName(r.name))}</h3><p>${r.agent==='claude'?'Claude Code':'Codex'} · ${esc(new Date(r.installed_at*1000).toLocaleString())} · ${r.status==='undone'?'Undone':'Installed'}</p><details><summary>Destination and source</summary><p class="source-path">${esc(r.root)}</p><p class="source-path">${esc(r.source)}</p>${r.backup?`<p class="source-path">Archived copy: ${esc(r.backup)}</p>`:''}</details>${r.rating?`<p class="rating-label">Your assessment: ${esc(r.rating)}</p>`:''}${r.ratingNote?`<p>${esc(r.ratingNote)}</p>`:''}${r.rating?`<button class="text-link" data-share-assessment="${i}">Share this assessment</button>`:''}</div><div class="history-actions"><button class="button" data-rate-install="${i}">${r.rating?'Edit assessment':'Was this useful?'}</button>${r.status==='installed'?`<button class="text-link" data-undo-install="${i}">Review undo</button>`:''}</div></article>`).join('')||'<p class="manage-note">No installs recorded yet. Your existing library is unchanged.</p>'}</div><p id="form-message" role="alert"></p>`);}
function ratingForm(index){const r=experienceHistory[index];showDialog(dialogHeader('Was '+esc(displaySkillName(r.name))+' useful?')+`<form id="rating-form" data-install="${r.id}"><p>This assessment is saved locally. Use Send feedback to share it with the project.</p><label for="skill-rating">Your experience</label><select id="skill-rating">${[['useful','Useful'],['confusing','Confusing'],['unused','Haven’t used it yet'],['','Clear assessment']].map(([v,label])=>`<option value="${v}" ${r.rating===v?'selected':''}>${label}</option>`).join('')}</select><label for="rating-note">What worked or got in the way?</label><textarea id="rating-note" maxlength="1000" rows="4">${esc(r.ratingNote||'')}</textarea><p id="form-message" role="alert"></p><button class="button primary">Save assessment</button></form>`);}
async function readinessDialog(){const run=++readinessRun;showDialog(dialogHeader('Agent readiness')+'<p>Checking CLI startup and saved sign-in. This does not send a prompt or consume inference usage.</p><p id="readiness-pending" role="status">Checking Codex and Claude Code…</p>');try{readinessData=(await api('/api/readiness',{})).agents;if(!modal.open||!$('#readiness-pending')||run!==readinessRun)return;showDialog(dialogHeader('Agent readiness')+`<p>These checks inspect local CLI startup and saved sign-in. They do not make an inference request.</p>${readinessData.map(r=>`<article class="readiness-entry"><div><h3>${esc(r.label)} <span class="readiness-status ${r.status==='ready'?'is-ready':''}">${esc(({ready:'Signed in',missing:'Not installed','sign-in':'Sign in needed',update:'Update needed',unknown:'Check needed'})[r.status])}</span></h3><p>${esc(r.message)}</p>${r.version?`<small>CLI version ${esc(r.version)}</small>`:''}${r.command?`<pre class="starter-prompt">${esc(r.command)}</pre>`:''}${r.status==='missing'?`<a class="text-link" href="${r.id==='codex'?'https://developers.openai.com/codex/cli/':'https://code.claude.com/docs/en/setup'}" target="_blank" rel="noopener">Installation instructions</a>`:''}</div></article>`).join('')}<button class="button" id="agent-readiness-retry">Check again</button>`);}catch(error){errorMessage(error.message);}}
function projectNotesForm(){const p=selectedProject();if(!p)return;showDialog(dialogHeader('How you work in '+esc(p.name))+`<form id="project-notes-form" data-project="${p.id}"><p>Describe what you use each agent for. Only the selected agent’s notes are included in its recommendation review. Notes stay local until you request that analysis.</p><label for="notes-codex">Codex use case</label><textarea id="notes-codex" maxlength="2000" rows="4" placeholder="Backend changes, database migrations, and tests…">${esc(p.notes?.codex||'')}</textarea><label for="notes-claude">Claude Code use case</label><textarea id="notes-claude" maxlength="2000" rows="4" placeholder="Interface design, copy, and frontend implementation…">${esc(p.notes?.claude||'')}</textarea><p id="form-message" role="alert"></p><button class="button primary">Save project notes</button></form>`);}
async function saveChoice(r,status,note='',context=null){const scope=context||{agent:recommendationResult.target,project:recommendationResult.project?.id||''};await api('/api/recommendation-choice',{skill:r.id||r.skill,agent:scope.agent,project:scope.project,status,note,reason:r.reason||'',firstStep:r.firstStep||''});}
function dismissalForm(index){const r=recommendationResult.recommendations[index];showDialog(dialogHeader('Why doesn’t this fit?')+`<form id="dismiss-recommendation-form" data-index="${index}"><p>${esc(displaySkillName(r.name))} won’t be suggested again for this agent and destination unless you reset this choice.</p><label for="dismissal-note">Optional note for future reviews</label><textarea id="dismissal-note" maxlength="500" rows="3" placeholder="I use Claude for design work, not backend debugging."></textarea><p id="form-message" role="alert"></p><button class="button primary">Mark not relevant</button></form>`);}
async function choicesDialog(){choiceData=await api('/api/recommendation-choices');const agent=projectSelection?projectAgent:recommendationResult?.target||usageConfig.provider||'codex';choiceData=choiceData.filter(c=>c.agent===agent&&c.project===projectSelection);showDialog(dialogHeader('Saved & dismissed suggestions')+`<p>${agent==='claude'?'Claude Code':'Codex'} · ${esc(selectedProject()?.name||'Personal library')}. These choices stay separate from your other agents and projects.</p>${choiceData.map((c,i)=>`<article class="choice-entry"><h3>${esc(displaySkillName(c.name))} <small>${c.status==='saved'?'Saved for later':'Not relevant'}</small></h3><p>${esc(c.reason||c.note)}</p>${c.note&&c.reason?`<p class="manage-note">Your note: ${esc(c.note)}</p>`:''}<div class="manage-actions">${c.status==='saved'?`<button class="button" data-review-saved="${i}">Review skill</button>`:''}<button class="text-link" data-reset-choice="${i}">Reset choice</button></div></article>`).join('')||'<p class="manage-note">Nothing saved or dismissed here yet.</p>'}<p id="form-message" role="alert"></p>`);}
function feedbackForm(prefill=''){showDialog(dialogHeader('Send feedback')+`<form id="feedback-form"><p>Prepare a report for the Skill-Desk GitHub project. You’ll review the exact text before opening a draft. No history, files, or logs are attached automatically.</p><label for="feedback-kind">What would you like to share?</label><select id="feedback-kind"><option>Bug</option><option>Idea</option><option>Confusing experience</option></select><label for="feedback-title">Short title</label><input id="feedback-title" required maxlength="120" placeholder="What happened or what would help?"><label for="feedback-message">Details</label><textarea id="feedback-message" required maxlength="5000" rows="6" placeholder="What were you trying to do? What happened? What did you expect?">${esc(prefill)}</textarea><p id="form-message" role="alert"></p><button class="button primary">Review report</button></form>`);}
function feedbackReview(report){showDialog(dialogHeader('Review your feedback')+`<p>Edit or remove anything you don’t want to share. GitHub drafts are public when submitted; opening a draft does not submit it.</p><label for="review-feedback-title">Issue title</label><input id="review-feedback-title" maxlength="140" value="${esc(report.title)}"><label for="review-feedback-body">Report</label><textarea id="review-feedback-body" rows="12" maxlength="7000">${esc(report.body)}</textarea><p id="form-message" role="status"></p><div class="manage-actions"><button class="button" id="copy-feedback">Copy report</button><button class="button primary" id="open-feedback">Open GitHub draft</button></div><p class="manage-note">You can also copy the report and share it another way. A GitHub account is required to submit an issue.</p>`);}
async function whatsNew(){const release=await api('/api/release');whatsNewShown=release.version;showDialog(dialogHeader('What’s new in '+esc(release.version))+`<p class="release-eyebrow">${esc(release.title)}</p><p>${esc(release.intro)}</p><div class="release-items">${release.items.map(item=>`<article><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><button class="text-link" data-release-action="${item.action}">${esc(item.label)} →</button></article>`).join('')}</div><p id="form-message" role="alert"></p><button class="button" id="dismiss-whats-new" data-version="${release.version}">Got it</button>`);}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(['installation-history','installation-history-menu','installation-history-settings'].includes(b.id)){await loadHistory();historyDialog();}
 if(b.dataset.rateInstall!==undefined)ratingForm(Number(b.dataset.rateInstall));
 if(b.dataset.undoInstall!==undefined){const r=experienceHistory[Number(b.dataset.undoInstall)];const preview=await api('/api/installation-undo-preview',{id:r.id});showDialog(dialogHeader('Undo '+esc(displaySkillName(preview.name))+'?')+`<p>The installed files match the original copy. Undo removes this skill from its library and keeps an archived copy in Skill-Desk’s local data.</p><p class="source-path">${esc(preview.destination)}</p><p>Files are checked again before removal. Modified skills are preserved.</p><p id="form-message" role="alert"></p><button class="button primary" id="confirm-install-undo" data-preview="${preview.preview}">Undo installation</button>`);}
 if(b.id==='confirm-install-undo'){b.disabled=true;await api('/api/installation-undo',{preview:b.dataset.preview});await loadManage();await syncCatalog();await loadHistory();historyDialog();toast('Installation undone. An archived copy was kept.');}
 if(['agent-readiness','agent-readiness-settings','agent-readiness-retry'].includes(b.id))await readinessDialog();
 if(b.id==='edit-project-notes')projectNotesForm();
 if(b.dataset.saveRecommendation!==undefined){const index=Number(b.dataset.saveRecommendation);await saveChoice(recommendationResult.recommendations[index],'saved');recommendationResult.recommendations.splice(index,1);renderManage();toast('Saved for this agent and destination');}
 if(b.dataset.dismissRecommendation!==undefined)dismissalForm(Number(b.dataset.dismissRecommendation));
 if(b.id==='saved-recommendations')await choicesDialog();
 if(b.dataset.resetChoice!==undefined){const c=choiceData[Number(b.dataset.resetChoice)];await saveChoice(c,'reset','',c);await choicesDialog();}
 if(b.dataset.reviewSaved!==undefined){if(activeDraft||activeJob)throw Error('Finish the current job or preview first.');const c=choiceData[Number(b.dataset.reviewSaved)];const draft=await api('/api/collection-preview',{collection:c.collection,names:[c.name],target:c.agent,project:c.project});draft.firstSteps={[c.name]:c.firstStep};previewPackage(draft);}
 if(b.dataset.shareAssessment!==undefined){const r=experienceHistory[Number(b.dataset.shareAssessment)];feedbackForm(`Skill: ${r.name}\nAgent: ${r.agent}\nMy assessment: ${r.rating}\n\n${r.ratingNote||''}`);}
 if(b.id==='send-feedback')feedbackForm();
 if(b.id==='copy-feedback'){await navigator.clipboard.writeText($('#review-feedback-title').value+'\n\n'+$('#review-feedback-body').value);toast('Feedback copied');}
 if(b.id==='open-feedback'){const title=$('#review-feedback-title').value,body=$('#review-feedback-body').value;const url='https://github.com/ldgraham92/skill-desk/issues/new?'+new URLSearchParams({title,body});if(url.length>7500){errorMessage('This report is too long for a draft link. Copy it, then paste it into a new GitHub issue.');const a=document.createElement('a');a.href='https://github.com/ldgraham92/skill-desk/issues/new';a.target='_blank';a.rel='noopener';a.textContent='Open a blank issue';$('#form-message').append(' ',a);}else window.open(url,'_blank','noopener');}
 if(b.id==='whats-new')await whatsNew();
 if(b.id==='dismiss-whats-new'){await api('/api/preferences',{whatsNew:b.dataset.version});whatsNewShown='';$('#whats-new-dot').hidden=true;modal.close();}
 if(b.dataset.releaseAction){const action=b.dataset.releaseAction;modal.close();if(action==='feedback')feedbackForm();else if(action==='history'){await loadHistory();historyDialog();}else{view='manage';await loadManage();await selectManageTab(action==='discover'?'discover':action==='recommendations'?'for-you':'installed');}}
 }catch(error){errorMessage(error.message);if(b.isConnected)b.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target;if(!['rating-form','project-notes-form','dismiss-recommendation-form','feedback-form'].includes(form.id))return;e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{
 if(form.id==='rating-form'){await api('/api/installation-rate',{id:form.dataset.install,rating:$('#skill-rating').value,note:$('#rating-note').value});await loadHistory();historyDialog();}
 if(form.id==='project-notes-form'){await api('/api/project-notes',{id:form.dataset.project,notes:{codex:$('#notes-codex').value,claude:$('#notes-claude').value}});await loadProjects();usageSample=null;modal.close();renderManage();toast('Project notes saved');}
 if(form.id==='dismiss-recommendation-form'){const index=Number(form.dataset.index);await saveChoice(recommendationResult.recommendations[index],'dismissed',$('#dismissal-note').value);recommendationResult.recommendations.splice(index,1);modal.close();renderManage();toast('Marked not relevant for this destination');}
 if(form.id==='feedback-form'){feedbackReview(await api('/api/feedback-preview',{kind:$('#feedback-kind').value,title:$('#feedback-title').value,message:$('#feedback-message').value,screen:view==='manage'?'Manage skills / '+manageTab:view}));}
 }catch(error){errorMessage(error.message);button.disabled=false;}});
window.addEventListener('DOMContentLoaded',async()=>{try{const [prefs,release]=await Promise.all([api('/api/preferences'),api('/api/release')]);if(prefs.whatsNew!==release.version){$('#whats-new-dot').hidden=false;if(prefs.walkthrough&&!modal.open&&!tour.open&&!activeJob&&!activeDraft&&!sessionStorage.getItem('skill-desk-job'))await whatsNew();}}catch(error){toast(error.message);}});

modal.addEventListener('close',()=>{if(!whatsNewShown)return;const version=whatsNewShown;whatsNewShown='';api('/api/preferences',{whatsNew:version}).then(()=>$('#whats-new-dot').hidden=true).catch(error=>toast(error.message));});
