'use strict';
let maintData=null,maintRows=[],maintReview=null,maintBackup=null,maintFile=null,maintQuality=null;
const maintApi=(op,data={})=>api('/api/workbench',{op,...data});
function maintFrame(title,body){showDialog(dialogHeader(title)+body+'<p id="form-message" role="alert"></p>');}
function maintDownload(value){const raw=atob(value.data),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/zip'}));const a=document.createElement('a');a.href=url;a.download=value.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function maintTextDownload(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function maintenanceHome(){const opener=modal.open?null:document.activeElement;maintData=await maintApi('overview');maintFrame('Maintain library',`<p>Review local changes, updates, backups, and recovery. Agent calls occur only when you explicitly start one.</p>${maintData.warnings.map(w=>`<p class="form-error">${esc(w)}</p>`).join('')}<div class="maint-grid">${[['search','Search and organize'],['updates','Upstream updates'],['collections','Local collections'],['duplicates','Find duplicates'],['backup','Backup and restore'],['recovery','Recover interrupted work'],['history','History controls'],['runs','Compare recommendation runs'],['projects','Reconnect or relocate']].map(([id,label])=>`<button class="button" data-maint-page="${id}">${label}</button>`).join('')}</div>`);if(opener)dialogReturnFocus=opener;}
function maintSearchForm(query={}){maintFrame('Search and organize',`<label for="maint-query">Search instructions and notes</label><input id="maint-query" type="search" value="${esc(query.text||'')}"><div class="maint-grid"><label>Agent<select id="maint-agent"><option value="">All agents</option>${agentOptions(query.agent||'')}</select></label><label>Project<select id="maint-project"><option value="">All projects</option>${projectData.map(p=>`<option value="${p.id}" ${query.project===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Origin<select id="maint-origin"><option value="">All origins</option>${['Existing','Repo Installed','User Created','Harness Copy','Package Imported','Markdown Imported'].map(v=>`<option ${v===query.origin?'selected':''}>${v}</option>`).join('')}</select></label><label>Tag<input id="maint-tag" value="${esc(query.tag||'')}"></label><label>Collection<input id="maint-collection" value="${esc(query.collection||'')}"></label><label>Modified after<input id="maint-modified" type="date" value="${query.modifiedAfter?new Date(query.modifiedAfter*1000).toISOString().slice(0,10):''}"></label></div><label class="checkbox-label"><input type="checkbox" id="maint-favorites" ${query.favorite?'checked':''}>Favorites only</label><div class="manage-actions"><button class="button primary" id="maint-search">Search</button><button class="button" id="maint-save-search">Save search</button></div><label>Saved search<select id="maint-saved-search"><option value="">Choose a saved search</option>${Object.keys(maintData.organization.searches).map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><button class="text-link" id="maint-delete-search">Delete selected search</button><div id="maint-results" aria-live="polite"></div>`);}
function maintQuery(){return {text:$('#maint-query').value,agent:$('#maint-agent').value,project:$('#maint-project').value,origin:$('#maint-origin').value,tag:$('#maint-tag').value,collection:$('#maint-collection').value,favorite:$('#maint-favorites').checked,modifiedAfter:$('#maint-modified').value?new Date($('#maint-modified').value).getTime()/1000:0};}
function maintPaintRows(result){maintRows=result.results;$('#maint-results').innerHTML=`<p>${maintRows.length} matching skills.${result.partial?' Search reached a scan limit.':''}</p><div class="manage-actions"><button class="button" data-maint-batch="favorite">Favorite selected</button><button class="button" data-maint-batch="export">Export selected</button><button class="button" data-maint-batch="archive">Review archive</button></div>${maintRows.map(r=>`<article class="readiness-entry"><label class="checkbox-label"><input type="checkbox" data-maint-select="${esc(r.id)}">${esc(r.name)}</label><p class="source-path">${esc(r.folder)}</p><p>${esc(r.harnesses.map(harnessLabel).join(', '))} · ${esc(r.origin)}</p><div class="manage-actions"><button class="button" data-maint-notes="${esc(r.id)}">Notes and tags</button><button class="button" data-maint-provenance="${esc(r.id)}">Origin and updates</button><button class="button" data-maint-quality="${esc(r.id)}">Check quality</button></div></article>`).join('')}`;}
function maintSelected(){return [...modal.querySelectorAll('[data-maint-select]:checked')].map(e=>e.dataset.maintSelect);}
async function maintPage(page){if(!maintData)maintData=await maintApi('overview');
 if(page==='search'){maintSearchForm();maintPaintRows(await maintApi('search',{query:{}}));}
 if(page==='updates'){const entries=maintData.entries;maintFrame('Upstream updates',`<p>Select up to ten imported skills to check. Checks download repository files for comparison; they do not install updates.</p>${entries.map(r=>`<label class="checkbox-label"><input type="checkbox" data-maint-select="${esc(r.id)}">${esc(r.name)}</label>`).join('')}<button class="button primary" id="maint-check-updates">Check selected sources</button>`);}
 if(page==='duplicates'){const r=await maintApi('duplicates');maintFrame('Duplicate review',`<p>Exact matches compare file names and bytes. Similar names are suggestions for manual review.${r.partial?' Comparison reached its limit.':''}</p><h3>Names in the same agent context</h3>${r.conflicts.map(c=>`<p>${esc(c.name)} · ${esc(harnessLabel(c.agent))} · ${esc(c.project||'Personal libraries')}. More than one copy is discoverable; review which one the agent selects.</p>`).join('')||'<p>No overlapping names in an agent context.</p>'}<h3>Exact copies</h3>${r.exact.map(group=>`<article class="readiness-entry">${group.map(x=>`<p>${esc(x.name)} · <span class="source-path">${esc(x.folder)}</span></p>`).join('')}</article>`).join('')||'<p>No exact copies.</p>'}<h3>Same names</h3>${r.names.map(group=>`<p>${group.map(x=>esc(x.name)+' in '+esc(x.library)).join('<br>')}</p>`).join('')||'<p>No repeated names.</p>'}<h3>Similar names</h3>${r.similar.map(x=>`<p>${esc(x.first.name)} / ${esc(x.second.name)}. ${esc(x.reason)}</p>`).join('')||'<p>No similar names found.</p>'}`);}
 if(page==='collections'){const r=await maintApi('collections');maintFrame('Local collections',`<p>Add collection names through a skill's Notes and tags editor. Copies are independent after installation.</p>${r.collections.map(c=>`<article class="readiness-entry"><h3>${esc(c.name)}</h3>${Object.entries(c.agents).map(([a,names])=>`<p>${esc(harnessLabel(a))}: ${names.map(esc).join(', ')||'No copies'}</p>`).join('')}<label>Copy destination<select data-collection-target="${esc(c.name)}">${agentOptions('codex')}</select></label><button class="button" data-collection-review="${esc(c.name)}">Review installation</button><button class="button" data-collection-quality="${esc(c.name)}">Export quality report</button></article>`).join('')||'<p>No local collections yet.</p>'}`);}
 if(page==='backup'){maintFrame('Backup and restore',`<p>Backups contain the selected local content and may include your private notes and filesystem paths. Review your selection before exporting.</p><label class="checkbox-label"><input id="maint-backup-settings" type="checkbox">Include application settings and project registrations</label><label class="checkbox-label"><input id="maint-backup-drafts" type="checkbox">Include explicitly saved drafts and revisions</label>${maintData.entries.map(r=>`<label class="checkbox-label"><input type="checkbox" data-maint-select="${esc(r.id)}">${esc(r.name)} · ${esc(r.library)}</label>`).join('')}<button class="button primary" id="maint-backup-export">Export selected backup</button><hr><label for="maint-backup-file">Restore a workspace backup</label><input id="maint-backup-file" type="file" accept=".zip"><button class="button" id="maint-backup-preview">Verify and preview restore</button>`);}
 if(page==='recovery'){maintFrame('Recover interrupted work',`<p>Recovery shows the destination and preserved copies before making changes.</p>${maintData.interrupted.map(j=>`<p role="status">Interrupted ${esc(j.action)} job. Start it again after reviewing your saved drafts. Inputs and prompt text were not persisted.</p>`).join('')}${maintData.recovery.filter(r=>!['complete','recovered'].includes(r.phase)).map(r=>`<article class="readiness-entry"><p>${esc(r.action||'Unreadable record')} · ${esc(r.phase)}</p><p class="source-path">${esc(r.destination||r.message)}</p>${r.phase!=='corrupt'?`<button class="button" data-recovery-review="${r.id}">Review recovery</button>`:''}</article>`).join('')||'<p>No unfinished filesystem operations.</p>'}`);}
 if(page==='runs'){const data=await maintApi('recommendation-runs');const options=data.runs.map(r=>`<option value="${r.id}">${esc(harnessLabel(r.target))} · ${esc(new Date(r.checkedAt*1000).toLocaleTimeString())} · ${r.sampled} excerpts</option>`).join('');maintFrame('Compare recommendation runs',`<p>Only runs from this app session are available. Evidence comparisons use fingerprints without persisting prompt text.</p><label>Earlier run<select id="maint-run-left">${options}</select></label><label>Later run<select id="maint-run-right">${options}</select></label><button class="button" id="maint-compare-runs" ${data.runs.length<2?'disabled':''}>Compare runs</button><div id="maint-runs-result"></div>`);}
 if(page==='history'){const samples=await maintApi('samples');maintFrame('History controls',`<p>Exclude these directories from future samples. Existing saved samples remain until you delete them.</p><label for="maint-exclude-projects">Project paths, one per line</label><textarea id="maint-exclude-projects" rows="4">${esc(maintData.exclusions.projects.join('\n'))}</textarea><label for="maint-exclude-locations">History locations, one per line</label><textarea id="maint-exclude-locations" rows="4">${esc(maintData.exclusions.locations.join('\n'))}</textarea><button class="button" id="maint-save-exclusions">Save exclusions</button><h3>Explicitly saved samples</h3>${samples.samples.map(s=>`<article class="readiness-entry"><p>${esc(harnessLabel(s.target))} · ${s.count} excerpts · ${esc(new Date(s.savedAt*1000).toLocaleString())}</p><button class="button" data-sample-open="${s.id}">Review sample</button><button class="text-link" data-sample-delete="${s.id}">Delete sample</button></article>`).join('')||'<p>No saved samples.</p>'}`);}
 if(page==='projects'){maintFrame('Reconnect or relocate',`<p>Reconnect a repository after moving it to retain its registration and notes.</p><label>Project<select id="maint-reconnect-project">${projectData.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>New repository path<input id="maint-reconnect-path"></label><button class="button" id="maint-reconnect-preview">Review reconnection</button><hr><label>New managed library directory<input id="maint-relocate-path"></label><p>Relocation preserves a directory link at the original location so agents can still find the skills. The original files are retained as a recovery copy.</p><button class="button" id="maint-relocate-preview">Review relocation</button>`);}
}
async function maintProvenance(id){const r=await maintApi('provenance',{id});maintFrame('Origin and upstream updates',`<p class="source-path">${esc(r.location)}</p><p>${esc(r.kind||'Existing')} · ${esc(r.created_at||'Import date unknown')}</p><p class="source-path">${esc(r.source||'No recorded source')}</p><p>${r.localChanges===null?'No comparison baseline is available.':r.localChanges?'Local files differ from the imported revision.':'Local files match the imported revision.'}</p>${r.upstream?`<p>Repository: ${esc(r.upstream.repo)}</p><p>Installed revision: ${esc(r.upstream.commit)}</p><label>Revision to check<input id="maint-upstream-ref" value="${esc(r.pin||r.upstream.ref||'')}" placeholder="Default branch, tag, or commit"></label><div class="manage-actions"><button class="button primary" data-upstream-check="${esc(id)}">Check revision</button><button class="button" data-upstream-pin="${esc(id)}">Pin entered commit</button><button class="button" data-pin-installed="${esc(id)}">Pin installed revision</button></div><p>Clear the field and choose Pin revision to remove the pin.</p>`:`<p>This skill needs a recorded repository baseline before upstream updates can be compared.</p>${r.kind==='Repo Installed'?`<button class="button" data-upstream-baseline="${esc(id)}">Read original revision and establish baseline</button>`:''}`}<h3>Archived revisions</h3>${(r.archives||[]).map(a=>`<button class="button model-option" data-rollback-id="${esc(id)}" data-rollback-token="${a.token}">Review rollback to ${esc(a.at)}</button>`).join('')||'<p>No archived revisions.</p>'}<h3>Operation history</h3>${r.updates.map(u=>`<p>${esc(u.action)} · ${esc(u.phase)} · ${esc(new Date(u.started*1000).toLocaleString())}</p>`).join('')||'<p>No operation records.</p>'}`);}
function maintUpdateReview(r){maintReview=r;maintFrame('Review upstream changes',`<p>${esc(r.previous)} → ${esc(r.commit)}</p><p>${r.localChanges?'Local edits will be preserved where they can be merged.':'No local edits detected.'}</p>${r.renames.map(x=>`<p>Possible rename: ${esc(x.previous)} → ${esc(x.current)}</p>`).join('')}${r.changes.map(x=>`<details><summary>${esc(x.action)} ${esc(x.file)}</summary><pre class="skill-preview">${esc(x.diff)}</pre></details>`).join('')||'<p>No file differences.</p>'}${r.conflicts.map((x,i)=>`<article class="readiness-entry"><h3>Conflict: ${esc(x.file)}</h3><label>Resolution<select data-resolution="${i}"><option value="">Choose a resolution</option><option value="local">Keep local${x.localDeleted?' deletion':''}</option><option value="upstream">Use upstream${x.upstreamDeleted?' deletion':''}</option><option value="custom">Use edited text below</option></select></label><label>Custom file contents<textarea data-resolution-text="${i}" rows="6" maxlength="200000"></textarea></label></article>`).join('')}<button class="button primary" id="maint-prepare-update">Prepare merged preview</button><button class="text-link" id="maint-discard-update">Discard update review</button>`);}
function showMaintenanceResult(result){if(result.workbenchType==='provenance'){maintProvenance(result.workbenchResult.id);return;}if(result.workbenchType==='update')maintUpdateReview(result.workbenchResult);else{maintFrame('Upstream check results',result.workbenchResult.map((r,i)=>`<article class="readiness-entry"><p class="source-path">${esc(r.folder)}</p>${r.error?`<p>${esc(r.error)}</p>`:`<p>${r.review.changes.length} file differences, ${r.review.conflicts.length} conflicts</p><button class="button" data-update-result="${i}">Review update</button>`}</article>`).join(''));modal.querySelectorAll('[data-update-result]').forEach(b=>b.onclick=()=>maintUpdateReview(result.workbenchResult[Number(b.dataset.updateResult)].review));}}
function maintDraftTools(){const s=selectedCandidate();maintFrame('Draft files and revisions',`<p>File changes create a separate preview. The current draft remains available.</p><div class="manage-actions"><button class="button" id="maint-markdown">Preview Markdown</button><button class="button" id="maint-add-file">Add text file</button><button class="button" id="maint-find-replace">Find and replace</button><button class="button" id="maint-tree-revisions">Restore revision</button><button class="button" id="maint-export-draft">Export draft</button><button class="button" id="maint-template-draft">Save as template</button></div>${s.files.map(f=>`<button class="button model-option" data-maint-file="${esc(f)}">${esc(f)}</button>`).join('')}<label>Fork for another agent<select id="maint-fork-agent">${agentOptions('codex')}</select></label><button class="button" id="maint-fork-draft">Create independent preview</button><button class="button" id="draft-back">Back to preview</button>`);}
function maintFileForm(file,content='',add=false){maintFile={file,add};maintFrame(add?'Add draft file':'Edit draft file',`<label>File path<input id="maint-file-path" value="${esc(file)}" ${add?'':'readonly'}></label><label>UTF-8 text<textarea id="maint-file-content" rows="16" maxlength="200000" spellcheck="false">${esc(content)}</textarea></label><button class="button primary" id="maint-file-save">Review file changes</button>${!add&&file!=='SKILL.md'?'<label>Rename to<input id="maint-file-rename"></label><button class="button" id="maint-file-rename-button">Review rename</button><button class="text-link" id="maint-file-remove">Review removal</button>':''}<button class="button" id="maint-draft-tools">Back to files</button>`);}
function maintChangedDraft(r){previewDraft(r);if(r.fileChanges?.length){const box=document.createElement('details');box.innerHTML='<summary>Supporting-file changes</summary>'+r.fileChanges.map(f=>`<h3>${esc(f.file)}</h3><pre class="skill-preview">${esc(f.diff)}</pre>`).join('');modal.querySelector('.manage-actions')?.before(box);}}
document.addEventListener('change',async e=>{if(e.target.id==='maint-saved-search'&&e.target.value){const q=maintData.organization.searches[e.target.value];maintSearchForm(q);maintPaintRows(await maintApi('search',{query:q}));}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.id==='maintenance')await maintenanceHome();
 if(b.dataset.maintPage)await maintPage(b.dataset.maintPage);
 if(b.id==='maint-search')maintPaintRows(await maintApi('search',{query:maintQuery()}));
 if(b.id==='maint-save-search'){const query=maintQuery();maintFrame('Save search','<label>Search name<input id="maint-search-name" maxlength="80"></label><button class="button primary" id="maint-confirm-search">Save</button>');$('#maint-confirm-search').onclick=async()=>{try{await maintApi('search-save',{name:$('#maint-search-name').value,query});await maintenanceHome();}catch(error){errorMessage(error.message);}};}
 if(b.id==='maint-delete-search'){await maintApi('search-save',{name:$('#maint-saved-search').value,delete:true});await maintenanceHome();}
 if(b.dataset.maintNotes){const id=b.dataset.maintNotes,entry=maintData.entries.find(x=>x.id===id),value=maintData.organization.skills[entry.folder]||{};maintFrame('Notes and tags',`<p>${esc(entry.name)}</p><label>Notes<textarea id="maint-notes" maxlength="10000" rows="6">${esc(value.notes||'')}</textarea></label><label>Tags, comma separated<input id="maint-tags" value="${esc((value.tags||[]).join(', '))}"></label><label>Collections, comma separated<input id="maint-collections" value="${esc((value.collections||[]).join(', '))}"></label><label class="checkbox-label"><input type="checkbox" id="maint-favorite" ${entry.favorite?'checked':''}>Favorite</label><button class="button primary" id="maint-save-notes">Save locally</button>`);$('#maint-save-notes').onclick=async()=>{try{await maintApi('annotate',{id,notes:$('#maint-notes').value,tags:$('#maint-tags').value.split(',').map(x=>x.trim()).filter(Boolean),collections:$('#maint-collections').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:$('#maint-favorite').checked});saved=(await api('/api/preferences')).saved;await maintenanceHome();}catch(error){errorMessage(error.message);}};}
 if(b.dataset.maintProvenance)await maintProvenance(b.dataset.maintProvenance);
 if(b.dataset.maintQuality){const id=b.dataset.maintQuality;const previous=maintQuality?.id===id?maintQuality:null;const r=await maintApi('quality',{id});maintQuality={id,...r};const resolved=previous?previous.issues.filter(x=>!r.issues.some(y=>x.code===y.code&&x.file===y.file)):[];maintFrame('Skill quality checks',`<p>${r.valid?'Installation checks passed.':'Blocking issues need correction before installation.'} Advisory checks help you review agent compatibility and portability.</p>${resolved.length?`<p>${resolved.length} previous findings resolved.</p>`:''}${r.issues.map(x=>`<article class="readiness-entry"><p>${esc(x.severity)} · ${esc(x.file)}</p><p>${esc(x.message)}</p></article>`).join('')||'<p>No findings.</p>'}${r.externalSkillReferences.map(x=>`<p>Possible external dependency in ${esc(x.file)}: ${esc(x.reference)}</p>`).join('')}<button class="button" data-maint-quality="${esc(id)}">Run checks again</button><button class="button" id="maint-export-quality">Export report</button>`);}
 if(b.id==='maint-export-quality')maintTextDownload('skill-quality.json',JSON.stringify(maintQuality,null,2));
 if(b.dataset.rollbackToken)previewDraft(await maintApi('rollback-preview',{id:b.dataset.rollbackId,token:b.dataset.rollbackToken}));
 if(b.dataset.upstreamBaseline)await startJob('workbench',{op:'upstream-baseline',id:b.dataset.upstreamBaseline});
 if(b.dataset.upstreamCheck)await startJob('workbench',{op:'update-check',id:b.dataset.upstreamCheck,revision:$('#maint-upstream-ref').value});
 if(b.dataset.pinInstalled){await maintApi('pin',{id:b.dataset.pinInstalled,revision:'installed'});toast('Installed revision pinned');}
 if(b.dataset.upstreamPin){await maintApi('pin',{id:b.dataset.upstreamPin,revision:$('#maint-upstream-ref').value});toast('Revision preference saved');}
 if(b.id==='maint-check-updates')await startJob('workbench',{op:'updates-check',ids:maintSelected()});
 if(b.id==='maint-prepare-update'){const resolutions={};maintReview.conflicts.forEach((x,i)=>{resolutions[x.file]={side:modal.querySelector(`[data-resolution="${i}"]`).value,content:modal.querySelector(`[data-resolution-text="${i}"]`).value};});previewDraft(await maintApi('update-prepare',{id:maintReview.id,resolutions}));}
 if(b.id==='maint-discard-update'){await maintApi('update-discard',{id:maintReview.id});await maintenanceHome();}
 if(b.dataset.maintBatch){const ids=maintSelected(),action=b.dataset.maintBatch;if(action==='archive'){const r=await maintApi('batch-review',{ids});maintFrame('Review archive',`<p>Move these managed skills into the local archive. Each result is reported separately.</p>${r.items.map(x=>`<p>${esc(x.name)} · ${esc(x.folder)}</p>`).join('')}<button class="button primary" id="maint-confirm-batch">Archive reviewed skills</button>`);$('#maint-confirm-batch').onclick=async()=>{try{const result=await maintApi('batch',{ids,action,fingerprints:Object.fromEntries(r.items.map(x=>[x.id,x.fingerprint]))});maintFrame('Archive results',`<pre class="skill-preview">${esc(JSON.stringify(result.results,null,2))}</pre>`);await loadManage();}catch(error){errorMessage(error.message);}};}else{const r=await maintApi('batch',{ids,action});if(action==='export'&&r.data)maintDownload(r);if(action==='favorite')saved=(await api('/api/preferences')).saved;maintFrame(action==='export'?'Export results':'Favorite results',`<pre class="skill-preview">${esc(JSON.stringify(r.results,null,2))}</pre>`);}}
 if(b.dataset.collectionQuality)maintTextDownload('collection-quality.json',JSON.stringify(await maintApi('collection-quality',{name:b.dataset.collectionQuality}),null,2));
 if(b.dataset.collectionReview){const name=b.dataset.collectionReview,target=[...modal.querySelectorAll('[data-collection-target]')].find(x=>x.dataset.collectionTarget===name).value;previewDraft(await maintApi('collection-preview',{name,target}));}
 if(b.id==='maint-backup-export'){b.disabled=true;maintDownload(await maintApi('backup-export',{ids:maintSelected(),settings:$('#maint-backup-settings').checked,drafts:$('#maint-backup-drafts').checked}));b.disabled=false;}
 if(b.id==='maint-backup-preview'){const file=$('#maint-backup-file').files[0];if(!file)throw Error('Choose a workspace backup.');if(file.size>100000000)throw Error('Backup exceeds 100 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));maintBackup=await maintApi('backup-preview',{data:btoa(binary)});maintFrame('Review workspace restore',`<p>${esc(maintBackup.message)}</p>${maintBackup.objects.map(x=>`<article class="readiness-entry"><label class="checkbox-label"><input type="checkbox" data-restore-select="${x.index}">${esc(x.kind)} · ${esc(x.name)}</label><p class="source-path">${esc(x.destination)}</p>${x.conflict?`<label class="checkbox-label"><input type="checkbox" data-restore-replace="${x.index}">Replace this existing destination</label>`:'<p>New destination</p>'}</article>`).join('')}<button class="button primary" id="maint-restore">Restore selected items</button><button class="text-link" id="maint-discard-restore">Discard review</button>`);}
 if(b.id==='maint-restore'){b.disabled=true;const selections=[...modal.querySelectorAll('[data-restore-select]:checked')].map(x=>({index:Number(x.dataset.restoreSelect),replace:!!modal.querySelector(`[data-restore-replace="${x.dataset.restoreSelect}"]`)?.checked}));const r=await maintApi('backup-restore',{id:maintBackup.id,selections});maintFrame('Restore results',`<pre class="skill-preview">${esc(JSON.stringify(r.results,null,2))}</pre>${r.restartRequired?'<p role="status">Restart Skill-Desk to load the restored settings.</p>':''}`);}
 if(b.id==='maint-discard-restore'){await maintApi('backup-discard',{id:maintBackup.id});await maintenanceHome();}
 if(b.dataset.recoveryReview){const r=await maintApi('recovery-preview',{id:b.dataset.recoveryReview});maintFrame('Review operation recovery',`<p>${esc(r.action)}</p><p class="source-path">${esc(r.destination)}</p><p>Any current files displaced by recovery are preserved with the operation record.</p>${r.canRestore?'<button class="button" id="maint-recover-before">Restore previous copy</button>':''}${r.canFinish?'<button class="button" id="maint-recover-after">Finish with prepared copy</button>':''}`);for(const mode of ['before','after'])$('#maint-recover-'+mode)?.addEventListener('click',async()=>{try{const result=await maintApi('recovery-apply',{id:r.id,expected:r.current,mode});if(result.restartRequired)maintFrame('Settings recovered','<p>Restart Skill-Desk to load the recovered settings.</p>');else await maintenanceHome();}catch(error){errorMessage(error.message);}});}
 if(b.id==='maint-reconnect-preview'||b.id==='maint-relocate-preview'){const reconnect=b.id==='maint-reconnect-preview',r=await maintApi(reconnect?'project-reconnect-preview':'relocate-preview',reconnect?{id:$('#maint-reconnect-project').value,path:$('#maint-reconnect-path').value}:{path:$('#maint-relocate-path').value});maintFrame(reconnect?'Review repository reconnection':'Review library relocation',`<p class="source-path">${esc(r.old||r.source)} → ${esc(r.new||r.target)}</p><p>${esc(r.message||'Keep the project identity and notes while changing its repository location.')}</p><button class="button primary" id="maint-confirm-move">Apply reviewed change</button>`);$('#maint-confirm-move').onclick=async()=>{try{const result=await maintApi(reconnect?'project-reconnect':'relocate',{id:r.id});maintFrame('Location updated',`<pre class="skill-preview">${esc(JSON.stringify(result,null,2))}</pre>`);await loadProjects();}catch(error){errorMessage(error.message);}};}
 if(b.id==='maint-compare-runs'){const r=await maintApi('recommendation-compare',{left:$('#maint-run-left').value,right:$('#maint-run-right').value});$('#maint-runs-result').innerHTML=`<p>${r.contextChanged?'Library or project inputs changed.':'Library and project inputs match.'}</p><pre class="skill-preview">${esc(JSON.stringify(r,null,2))}</pre>`;}
 if(b.id==='maint-save-exclusions'){await maintApi('history-options',{projects:$('#maint-exclude-projects').value.split('\n').map(x=>x.trim()).filter(Boolean),locations:$('#maint-exclude-locations').value.split('\n').map(x=>x.trim()).filter(Boolean)});await maintenanceHome();}
 if(b.dataset.sampleDelete){await maintApi('sample-delete',{id:b.dataset.sampleDelete});await maintPage('history');}
 if(b.dataset.sampleOpen){usageSample=await maintApi('sample-open',{id:b.dataset.sampleOpen});usageSample.excerpts.forEach(x=>x.selected=true);usageConfig.provider=usageSample.target;modal.close();view='manage';manageTab='for-you';renderManage();}
 if(b.id==='maint-save-sample'){const excerpts=usageSample.excerpts.filter(x=>x.selected).map(x=>({id:x.id,text:x.text}));await maintApi('sample-save',{preview:usageSample.preview,provider:usageSample.target,excerpts});toast('Reviewed excerpts saved locally');}
 if(b.id==='maint-draft-tools')maintDraftTools();
 if(b.id==='maint-markdown'){const text=selectedCandidate().content;maintFrame('Markdown preview',`<p>Basic preview. Embedded HTML and remote resources remain inactive.</p><div class="maint-markdown">${maintMarkdown(text)}</div><details><summary>Source instructions</summary><pre class="skill-preview">${esc(text)}</pre></details><button class="button" id="maint-draft-tools">Back to files</button>`);}
 if(b.dataset.maintFile){const r=await api('/api/draft-file',{...draftKey(),file:b.dataset.maintFile});if(!r.previewable)throw Error(r.message);maintFileForm(r.file,r.content);}
 if(b.id==='maint-add-file')maintFileForm('','',true);
 if(b.id==='maint-file-save'||b.id==='maint-file-remove'||b.id==='maint-file-rename-button'){const change=b.id==='maint-file-save'?{action:maintFile.add?'add':'edit',file:$('#maint-file-path').value,content:$('#maint-file-content').value}:b.id==='maint-file-remove'?{action:'remove',file:maintFile.file}:{action:'rename',file:maintFile.file,to:$('#maint-file-rename').value};maintChangedDraft(await maintApi('draft-files',{...draftKey(),expected:selectedCandidate().treeDigest,changes:[change]}));}
 if(b.id==='maint-find-replace'){maintFrame('Find and replace draft text','<p>Review all changed files in a new preview before installation.</p><label>Find<textarea id="maint-find" rows="3"></textarea></label><label>Replace with<textarea id="maint-replacement" rows="3"></textarea></label><button class="button primary" id="maint-run-replace">Prepare changes</button>');}
 if(b.id==='maint-run-replace')maintChangedDraft(await maintApi('draft-replace-text',{...draftKey(),expected:selectedCandidate().treeDigest,find:$('#maint-find').value,replacement:$('#maint-replacement').value}));
 if(b.id==='maint-export-draft')maintDownload(await maintApi('draft-export',draftKey()));
 if(b.id==='maint-template-draft'){await maintApi('draft-template',draftKey());toast('Reusable draft saved locally');}
 if(b.id==='maint-fork-draft')previewDraft(await maintApi('draft-fork',{...draftKey(),target:$('#maint-fork-agent').value}));
 if(b.id==='maint-tree-revisions'){const r=await maintApi('draft-revisions',draftKey());maintFrame('Restore a draft revision',`<p>Restoring creates an independent preview and preserves the current draft.</p>${r.revisions.map(x=>`<button class="button model-option" data-tree-revision="${x.index}">${esc(new Date(x.at*1000).toLocaleString())} · ${esc(x.digest.slice(0,12))}</button>`).join('')||'<p>No earlier folder revisions.</p>'}<button class="button" id="maint-draft-tools">Back to files</button>`);modal.querySelectorAll('[data-tree-revision]').forEach(button=>button.onclick=async()=>{try{previewDraft(await maintApi('draft-restore',{...draftKey(),expected:r.current,index:Number(button.dataset.treeRevision)}));}catch(error){errorMessage(error.message);}});}
}catch(error){errorMessage(error.message);if(b.isConnected)b.disabled=false;}});

function maintMarkdown(text){let code=false;return text.split('\n').map(line=>{if(/^```/.test(line)){code=!code;return code?'<pre>':'</pre>';}if(code)return esc(line)+'\n';const heading=line.match(/^(#{1,6})\s+(.*)$/);if(heading)return `<h${heading[1].length}>${esc(heading[2])}</h${heading[1].length}>`;return line.trim()?'<p>'+esc(line).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')+'</p>':'';}).join('')+(code?'</pre>':'');}
