'use strict';
const walkthroughSteps=[
 {image:'library',title:'A home for your skills',text:'Manage skills brings your installed skills, collections, and recommendations together. Open a skill for details, or use its menu for occasional actions.',alt:'Manage skills with a readable installed skills list and Installed, Discover, and For you tabs.'},
 {image:'projects',title:'Keep each project’s skills together',text:'Add an existing local repository, then choose it in Working in. Select Codex or Claude Code for that project. Personal libraries remain available in the same dropdown.',alt:'Project destination selector showing an onboarded repository and the agent selection.'},
 {image:'discover',title:'Choose what you need',text:'Discover includes AI Hero and PStack. Select individual skills, review their instructions and destination, then install. Existing files are never overwritten.',alt:'Discover collection with individual skills available for selection and a review button.'},
 {image:'recommendations',title:'Find gaps, avoid duplicates',text:'For you uses the selected agent to review its own recent history. Preview and edit excerpts first. Recommendations explain what to add and what is already covered by your library. Analysis uses your agent’s normal service and allowance.',alt:'Recommendations with reasons and an Already covered by your library comparison.'},
 {image:'first-step',title:'Put a skill to work',text:'After installing, copy a first-step prompt into a new session with the destination agent. Adapt it to your task. You can also print a cheatsheet from Quick reference and look for Update Ready in the sidebar.',alt:'Post-installation dialog with a starter prompt and Copy first step button.'}
];
const tour=document.createElement('dialog');tour.className='walkthrough-dialog';tour.setAttribute('aria-labelledby','walkthrough-title');document.body.append(tour);
const tourImage=document.createElement('dialog');tourImage.className='walkthrough-zoom';tourImage.setAttribute('aria-label','Walkthrough screenshot');document.body.append(tourImage);
let walkthroughIndex=0, walkthroughSaving=false;
function renderWalkthrough(){const step=walkthroughSteps[walkthroughIndex];tour.innerHTML=`<div class="walkthrough-top"><span>GETTING STARTED · ${walkthroughIndex+1} / ${walkthroughSteps.length}</span><button class="text-link" id="walkthrough-skip">Skip tour</button></div><div class="walkthrough-image"><img src="/walkthrough/${step.image}.png" alt="${esc(step.alt)}" width="1600" height="1000"><span>Example workspace</span><button class="button" id="walkthrough-enlarge">Enlarge screenshot</button></div><div class="walkthrough-copy"><h2 id="walkthrough-title" tabindex="-1">${esc(step.title)}</h2><p>${esc(step.text)}</p><p id="walkthrough-error" role="alert"></p></div><div class="walkthrough-footer"><button class="button" id="walkthrough-back" ${walkthroughIndex===0?'disabled':''}>Back</button><span class="walkthrough-dots" aria-label="Step ${walkthroughIndex+1} of ${walkthroughSteps.length}">${walkthroughSteps.map((_,i)=>`<span class="${i===walkthroughIndex?'current':''}"></span>`).join('')}</span><button class="button primary" id="walkthrough-next">${walkthroughIndex===walkthroughSteps.length-1?'Start exploring':'Next'}</button></div>`;}
function openWalkthrough(){if(modal.open||tour.open){toast('Close the current dialog to open the tour.');return;}walkthroughIndex=0;renderWalkthrough();tour.showModal();$('#walkthrough-next').focus();}
async function finishWalkthrough(){if(walkthroughSaving)return;walkthroughSaving=true;try{await api('/api/preferences',{walkthrough:1});tour.close();}catch(error){$('#walkthrough-error').textContent=error.message;}finally{walkthroughSaving=false;}}
tour.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||walkthroughSaving)return;if(b.id==='walkthrough-enlarge'){const step=walkthroughSteps[walkthroughIndex];tourImage.innerHTML=`<div class="zoom-heading"><strong>${esc(step.title)}</strong><button class="button" id="close-walkthrough-image">Back to tour</button></div><img src="/walkthrough/${step.image}.png" alt="${esc(step.alt)}">`;tourImage.showModal();$('#close-walkthrough-image').onclick=()=>tourImage.close();}if(b.id==='walkthrough-skip')finishWalkthrough();if(b.id==='walkthrough-back'&&walkthroughIndex>0){walkthroughIndex--;renderWalkthrough();$('#walkthrough-title').focus();}if(b.id==='walkthrough-next'){if(walkthroughIndex===walkthroughSteps.length-1)finishWalkthrough();else{walkthroughIndex++;renderWalkthrough();$('#walkthrough-title').focus();}}});
tour.addEventListener('cancel',e=>{e.preventDefault();finishWalkthrough();});
const tourLauncher=document.createElement('button');tourLauncher.className='walkthrough-launch';tourLauncher.textContent='Getting started';tourLauncher.onclick=openWalkthrough;document.querySelector('.sidebar footer').before(tourLauncher);
window.addEventListener('DOMContentLoaded',async()=>{try{const preferences=await api('/api/preferences');if(!preferences.walkthrough&&!modal.open&&!activeJob&&!activeDraft&&!sessionStorage.getItem('skill-desk-job'))openWalkthrough();}catch(error){toast('Could not load the getting-started guide. '+error.message);}});
