'use strict';
let manageTab='installed', librarySource='all', collectionData=null, collectionError='', activeCollection=null;
let collectionTarget='shared', collectionSelection=new Set();
let usageInfo=null, usageError='', usageSample=null, usageBusy=false, recommendationResult=null;
let usageRevision=0;
let usageConfig={provider:'',days:30,scope:'project'};
let projectData=[], projectSelection='', projectAgent='codex';
function selectedProject(){return projectData.find(p=>p.id===projectSelection);}
function scopeMatches(s){return (s.project||'')===projectSelection;}
function scopeBar(){return `<div class="scope-bar"><label for="project-scope">Working in</label><select id="project-scope"><option value="">Personal libraries</option>${projectData.map(p=>`<option value="${p.id}" ${p.id===projectSelection?'selected':''}>${esc(p.name)}${p.available?'':' · Unavailable'}</option>`).join('')}</select>${projectSelection?`<label for="project-agent">Agent</label><select id="project-agent">${agentOptions(projectAgent)}</select>`:''}${projectSelection&&['codex','claude'].includes(projectAgent)?'<button class="text-link" id="edit-project-notes">Project notes</button>':''}<button class="text-link" id="onboard-project">Add project</button><button class="text-link" id="manage-projects">Manage projects</button></div>`;}
async function loadProjects(){projectData=await api('/api/projects');if(projectSelection&&!selectedProject())projectSelection='';if(view==='manage'&&!modal.open)renderManage();}

const documentIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/></svg>';
function displaySkillName(name){return ({tdd:'Test-driven development', 'ai-hero':'AI Hero', pstack:'PStack'})[name]||String(name).replace(/[-_]/g,' ').replace(/^./,s=>s.toUpperCase());}
function shortDescription(text){const value=String(text||'Open this skill to see its instructions.').replace(/\s+/g,' ').trim();return value.length>160?value.slice(0,157)+'…':value;}
function sourceLabel(skill){
 if(/mattpocock|^AI Hero/.test(skill.source||''))return 'AI Hero';
 if(/cursor\/plugins|^PStack/.test(skill.source||''))return 'PStack';
 return {'User Created':'Created here','Repo Installed':'Repository','Markdown Imported':'Markdown','Harness Copy':'Copied','Package Imported':'Package','Existing':'Other'}[skill.kind]||'Other';
}
function libraryHeader(){return `<div class="library-heading"><div><h1>Manage skills</h1><p>Choose the skills you work with.</p></div><div class="library-tools">${typeof multiCopy!=='undefined'&&multiCopy?'<button class="button" id="resume-multi-copy">Review pending copies</button>':''}<button class="button" id="library-settings">Library settings</button><details class="action-menu" id="add-skills-menu"><summary class="button primary">Add skills <span aria-hidden="true">⌄</span></summary><div class="action-popover"><button data-manage-tab="discover">Browse collections</button><button id="create-skill">Create with an agent</button><button id="import-skill">Import from GitHub or Markdown</button><button id="import-package">Import a package</button><button id="nearby-receive">Receive from a device</button><button id="export-package">Export a package</button><button id="saved-drafts">Saved drafts</button><button id="maintenance">Maintain library</button><button id="installation-history-menu">Installation history</button></div></details></div></div><nav class="library-tabs" aria-label="Manage skills sections">${[['installed','Installed'],['discover','Discover'],['for-you','For you']].map(([id,label])=>`<button data-manage-tab="${id}" aria-current="${manageTab===id?'page':'false'}">${label}${id==='for-you'?'<span aria-hidden="true">✦</span>':''}</button>`).join('')}</nav>`;}
function installedWorkspace(){
 const all=manageData.installed.filter(s=>scopeMatches(s)&&(projectSelection?(s.harnesses||[]).includes(projectAgent):matchesHarness(s)));
 const rows=all.filter(s=>(librarySource==='all'||sourceLabel(s)===librarySource)&&query.toLowerCase().trim().split(/\s+/).every(t=>[s.name,s.description,sourceLabel(s)].join(' ').toLowerCase().includes(t)));
 const sources=[...new Set(manageData.installed.filter(scopeMatches).map(sourceLabel))].sort();
 return `<div class="library-toolbar"><span>${rows.length===all.length?all.length:rows.length+' of '+all.length} installed</span><label class="visually-hidden" for="library-source">Filter by source</label><select id="library-source"><option value="all">All sources</option>${sources.map(s=>`<option ${librarySource===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="library-list">${rows.map(s=>`<article class="library-row"><span class="skill-document">${documentIcon}</span><button class="library-name" data-library-detail="${esc(s.id)}">${esc(displaySkillName(s.name))}${s.error?'<small class="form-error">Needs attention</small>':''}${s.duplicates?.length?'<small>Multiple copies</small>':''}</button><p>${esc(shortDescription(s.description))}</p><span class="library-origin">${esc(sourceLabel(s))}</span><span class="library-provider">${(s.harnesses||[]).map(harnessLabel).join(' · ')}</span><details class="action-menu row-menu"><summary aria-label="Actions for ${esc(s.name)}">•••</summary><div class="action-popover"><button data-library-detail="${esc(s.id)}">Skill details</button>${s.readOnly?'':`<button data-remove="${esc(s.id)}">Remove and archive</button>`}</div></details></article>`).join('')||`<div class="library-empty"><h2>${all.length?'No matching skills':'Your library starts here'}</h2><p>${all.length?'Try another search or source.':'Explore the collections, or find skills that fit your recent work.'}</p><button class="button" data-manage-tab="discover">Explore collections</button></div>`}</div><div class="library-history-link"><button class="text-link" id="installation-history">Installation history & usefulness</button></div><button class="library-removed" id="show-removed">Removed skills${manageData.archived.length?' · '+manageData.archived.length:''} <span aria-hidden="true">›</span></button><div class="library-suggestion"><span>Find skills for the way you work</span><button class="text-link" data-manage-tab="for-you">Get recommendations <span aria-hidden="true">→</span></button></div>`;
}
function installedForTarget(name){return manageData.installed.some(s=>scopeMatches(s)&&s.name===name&&(collectionTarget==='shared'?!s.readOnly:(s.harnesses||[]).includes(collectionTarget)));}
function targetSelect(){if(projectSelection)return `<span>Install for ${harnessLabel(projectAgent)} in ${esc(selectedProject()?.name||'project')}</span>`;return `<label for="collection-target">Install into</label><select id="collection-target">${[['shared','Default skill library'],['codex','Codex'],['claude','Claude Code'],['opencode','OpenCode'],['cursor','Cursor']].map(([id,label])=>`<option value="${id}" ${collectionTarget===id?'selected':''}>${label}</option>`).join('')}</select>`;}
function discoverWorkspace(){
 if(!collectionData)return `<div class="library-empty"><p>${esc(collectionError||'Loading collections…')}</p>${collectionError?'<button class="button" id="retry-collections">Try again</button>':''}</div>`;
 const selected=collectionData.find(c=>c.id===activeCollection);
 if(!selected)return `<div class="section-intro"><h2>Skill collections</h2><p>Two curated collections. Choose individual skills or take a package with you.</p></div><div class="discover-list">${collectionData.map(c=>`<article class="discover-row"><div class="collection-mark" aria-hidden="true">${c.id==='ai-hero'?'A':'P'}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p><span>${c.count} skills · Bundled for offline use</span></div><button class="button" data-open-collection="${c.id}">Browse skills <span aria-hidden="true">→</span></button></article>`).join('')}</div><div class="library-suggestion"><span>Not sure where to start?</span><button class="text-link" data-manage-tab="for-you">Find your matches <span aria-hidden="true">→</span></button></div>`;
 const rows=selected.skills.filter(s=>[s.name,s.description].join(' ').toLowerCase().includes(query.toLowerCase().trim()));
 const chosen=selected.skills.filter(s=>collectionSelection.has(s.name)&&!installedForTarget(s.name)).map(s=>s.name);
 return `<button class="text-link collection-back" id="back-collections">← All collections</button><div class="collection-heading"><div><h2>${esc(selected.name)}</h2><p>${selected.count} skills · Select the ones you want to try.</p></div><button class="button" data-save-collection="${selected.id}">Save package</button></div><div class="collection-toolbar"><div>${targetSelect()}</div><button class="text-link" id="select-collection-shown">Select available</button><button class="text-link" id="clear-collection-selection">Clear</button></div><div class="collection-skills">${rows.map(s=>`<label class="collection-skill"><input type="checkbox" data-collection-skill="${esc(s.name)}" ${installedForTarget(s.name)?'disabled':collectionSelection.has(s.name)?'checked':''}><span><strong>${esc(displaySkillName(s.name))}</strong><small>${esc(shortDescription(s.description))}</small></span>${installedForTarget(s.name)?'<span class="installed-label">Installed</span>':''}</label>`).join('')||'<p>No matching skills.</p>'}</div><div class="collection-review-bar"><span id="collection-selection-count">${chosen.length} selected</span><button class="button primary" id="review-collection-selection" ${chosen.length?'':'disabled'}>Review selected skills</button></div><details class="collection-provenance"><summary>Source and packaging details</summary><p><a href="${esc(selected.url)}" target="_blank" rel="noopener">Original repository</a> · MIT license · ${esc(selected.commit.slice(0,7))}</p>${selected.adaptations.length?`<ul>${selected.adaptations.map(a=>`<li>${esc(a)}</li>`).join('')}</ul>`:'<p>Original skill folders and licenses are included.</p>'}</details><p id="form-message" role="status"></p>`;
}
async function loadCollections(){try{collectionError='';collectionData=await api('/api/collections');}catch(e){collectionError=e.message;}if(view==='manage'&&manageTab==='discover')renderManage();}
async function loadUsageInfo(){try{usageError='';usageInfo=await api('/api/usage-sources');usageConfig.provider=projectSelection?projectAgent:usageInfo.providers.find(p=>p.id===usageInfo.selected&&p.installed&&p.historyAnalysis)?.id||usageInfo.providers.find(p=>p.installed&&p.historyAnalysis)?.id||'';}catch(e){usageError=e.message;}if(view==='manage'&&manageTab==='for-you')renderManage();}
function recommendationSetup(){
 if(!usageInfo)return `<div class="library-empty"><p>${esc(usageError||'Checking available agents and history…')}</p>${usageError?'<button class="button" id="retry-usage-info">Try again</button>':''}</div>`;
 return `<div class="section-intro"><h2>Start with your recent work</h2><p>Find useful skills in AI Hero and PStack, based on your work with the agent you install them for.</p></div><div class="recommendation-utilities"><button class="text-link" id="agent-readiness">Check agent readiness</button><button class="text-link" id="saved-recommendations">Saved & dismissed suggestions</button></div><div class="usage-controls"><div><label for="usage-provider">Find skills for</label><select id="usage-provider" ${usageBusy||projectSelection?'disabled':''}>${usageInfo.providers.some(p=>p.installed&&p.historyAnalysis)?'':'<option value="">No agent available</option>'}${usageInfo.providers.filter(p=>p.historyAnalysis).map(p=>`<option value="${p.id}" ${usageConfig.provider===p.id?'selected':''} ${p.installed?'':'disabled'}>${esc(p.label)}${p.installed?'':' · Not installed'}</option>`).join('')}</select></div><div><label for="usage-days">Timeframe</label><select id="usage-days" ${usageBusy?'disabled':''}>${[7,30,90].map(days=>`<option value="${days}" ${usageConfig.days===days?'selected':''}>Last ${days} days</option>`).join('')}</select></div><div><label for="usage-scope">History scope</label><select id="usage-scope" ${usageBusy?'disabled':''}>${projectSelection?`<option value="project" ${usageConfig.scope==='project'?'selected':''}>This project only</option>`:''}<option value="all" ${!projectSelection||usageConfig.scope==='all'?'selected':''}>All projects</option></select></div><button class="button primary" id="preview-usage" ${usageBusy||!usageInfo.sources.some(s=>s.id===usageConfig.provider&&s.available)?'disabled':''}>${usageBusy?'Reading history…':usageSample?'Refresh history':'Preview history'}</button></div><p class="manage-note">${usageConfig.provider==='claude'?'Claude Code':'Codex'} reviews its own history. Recommended skills install into ${esc(selectedProject()?.name||'its personal library')}. ${projectSelection&&usageConfig.scope==='project'?'Only prompts identified with this repository are included. Prompts without repository metadata are excluded.':'The sample covers this agent’s recent work across projects; deselect unrelated excerpts.'}${usageConfig.provider&&!usageInfo.sources.some(s=>s.id===usageConfig.provider&&s.available)?' No history found for this agent.':''}</p><p class="usage-explanation">Review the excerpts before your agent analyzes them. Your selected excerpts, installed skill descriptions, bundled skill descriptions, and project name are sent to the selected agent’s service. Analysis uses its normal usage allowance. This preview samples conversation history; it does not measure tokens, billing, or account usage limits.</p>${usageConfig.provider?'':'<p class="form-error">Install and sign in to Codex or Claude Code, then refresh this page. </p>'}${usageError?`<p class="form-error" role="alert">${esc(usageError)}</p>`:''}${usageSample?usageReview():''}`;
}
function usageCoverage(){
 if(!usageSample)return '';
 return `<section class="history-coverage" aria-label="History coverage"><p role="status">Checked ${esc(new Date(usageSample.checkedAt*1000).toLocaleString())}. ${usageSample.partial?'Partial sample.':'Scan completed within the configured limits.'} ${usageSample.sampled} of ${usageSample.found} eligible prompts found.</p>${Object.entries(usageSample.coverage||{}).map(([source,c])=>`<p>${esc(harnessLabel(source))}: ${c.sessionsFound} session files found · ${c.sessionsScanned} scanned · ${c.sessionsSkipped} skipped${c.subagentSessions?' ('+c.subagentSessions+' delegated sessions)':''}${c.budgetSkippedSessions?' ('+c.budgetSkippedSessions+' beyond read limit)':''} · ${c.sessionsIncluded} represented in excerpts${c.unreadableFiles?' · '+c.unreadableFiles+' unreadable files':''}${c.duplicates?' · '+c.duplicates+' duplicate records removed':''}${c.excludedPrompts?' · '+c.excludedPrompts+' excluded by your settings':''}${c.timeExcluded?' · '+c.timeExcluded+' outside the timeframe':''}${c.scopeExcluded?' · '+c.scopeExcluded+' outside project scope':''}${c.instructionExcluded?' · '+c.instructionExcluded+' non-task records excluded':''}.</p>`).join('')}<details><summary>How this sample is selected</summary><p>Excerpts rotate across projects and dates. Counts describe local files discovered within the scan limits, not total account activity. Global history files can also contribute prompts. Project names come from recorded working directories and may identify a subfolder.</p><p>Limits: ${usageSample.limits?.excerpts||120} excerpts, ${usageSample.limits?.charactersPerExcerpt||1000} characters each, ${Math.round((usageSample.limits?.scanBytes||32000000)/1000000)} MB read. Large sessions contribute their beginning and windows distributed through the file, including the recent end. Missing context after a gap is excluded from project-only history.</p></details><details><summary>Prompts found by date and project</summary><p>Counts cover the retained scan results, before the excerpt limit. Dates use UTC.${usageSample.breakdownPartial?' Some earlier scan results were dropped to keep memory bounded.':''}</p><table><thead><tr><th>Date</th><th>Project</th><th>Prompts</th></tr></thead><tbody>${(usageSample.breakdown||[]).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.project)}</td><td>${r.found}</td></tr>`).join('')}</tbody></table></details><button class="button" id="preview-deeper" ${activeJob?'disabled':''}>Run deeper scan · 128 MB limit</button><p class="manage-note">Replaces this sample and its edits. You can cancel the deeper scan.</p></section>`;
}
function usageReview(){return `<section class="usage-review"><div class="collection-heading"><div><h3>${usageSample.sampled} excerpt${usageSample.sampled===1?'':'s'} to review</h3><p>${usageSample.scope==='project'?'This project only: '+esc(usageSample.project.name):'All projects'}. Replies and tool output are excluded.</p></div><button class="text-link" id="maint-save-sample">Save reviewed sample locally</button><button class="text-link" id="discard-usage">Discard sample</button></div>${usageCoverage()}<p class="manage-note">Common credential patterns and home paths are masked. Check the text and remove anything you do not want analyzed.</p>${usageSample.notes.map(n=>`<p class="manage-note">${esc(n)}</p>`).join('')}${usageSample.project?.notes?.[usageConfig.provider]?`<details class="review-context"><summary>Project notes included in this review</summary><p>${esc(usageSample.project.notes[usageConfig.provider])}</p></details>`:''}${(usageSample.choices||[]).some(c=>c.note)?`<details class="review-context"><summary>Preference notes included in this review</summary>${usageSample.choices.filter(c=>c.note).map(c=>`<p>${esc(c.name)}: ${esc(c.note)}</p>`).join('')}</details>`:''}${typeof excerptFilters==='function'?excerptFilters():''}<div class="usage-selection-tools"><button class="text-link" id="select-usage-all">Select all</button><button class="text-link" id="select-usage-none">Clear selection</button></div><div class="usage-excerpts">${usageSample.excerpts.map((e,i)=>`<article><label><input type="checkbox" data-usage-selected="${e.id}" ${e.selected?'checked':''}>${esc(({codex:'Codex',claude:'Claude Code',opencode:'OpenCode'})[e.source])} · ${esc(e.date)} · ${esc(e.project||'Project unknown')}</label><textarea aria-label="Usage excerpt ${i+1}" data-usage-text="${e.id}" maxlength="1000" rows="3">${esc(e.text)}</textarea></article>`).join('')||'<p>No recent prompts were found. Try another source or a longer timeframe.</p>'}</div><div class="usage-review-actions"><span id="usage-selected-count"></span><button class="button primary" id="run-recommendations" ${!usageSample.excerpts.length||!usageConfig.provider||activeJob?'disabled':''}>Ask ${usageConfig.provider==='claude'?'Claude Code':'Codex'} for recommendations</button></div></section>`;}
function recommendationInstalled(r){
 const scope=recommendationResult.project?.id||'';
 return manageData.installed.some(s=>s.name.toLowerCase()===r.name.toLowerCase()&&(s.harnesses||[]).includes(recommendationResult.target)&&(!s.project||s.project===scope));
}
function recommendationsWorkspace(){
 if(projectSelection&&['opencode','cursor'].includes(projectAgent))return `<div class="library-empty"><h2>${harnessLabel(projectAgent)} skills</h2><p>You can discover, import, and create skills for this agent. Automatic history recommendations currently support Codex and Claude Code only. This agent's history is not read or sent to another provider.</p><button class="button" data-manage-tab="discover">Explore collections</button></div>`;
 if(!recommendationResult)return recommendationSetup();
 const agent=harnessLabel(recommendationResult.target),destination=recommendationResult.project?.name||'Personal library';
 return `<div class="section-intro recommendation-intro"><div><h2>Recommended skills</h2><p>Choose a skill to review, then confirm installation.</p><small>${esc(agent)} · ${esc(destination)}</small><details class="recommendation-context"><summary>Based on ${recommendationResult.sampled} reviewed prompt${recommendationResult.sampled===1?'':'s'}</summary><p>${esc(recommendationResult.summary)}</p></details></div><div class="result-tools"><button class="text-link" id="saved-recommendations">Saved & dismissed suggestions</button><button class="text-link" id="new-recommendations">Start a new review</button></div></div><div class="recommendation-list">${recommendationResult.recommendations.map((r,i)=>{
  const installed=recommendationInstalled(r);
  return `<article class="recommendation-row"><div><span class="recommendation-source">${esc(r.collectionName)}</span><h3>${esc(displaySkillName(r.name))}</h3><p>${esc(r.reason)}</p><details class="recommendation-evidence"><summary>Why this was suggested</summary>${r.evidence.map(e=>`<blockquote><small>${esc(e.source)} · ${esc(e.date)} · ${esc(e.project||'Project unknown')} · ${esc(e.id)}</small><p>${esc(e.text)}</p></blockquote>`).join('')}</details></div><div class="recommendation-actions">${installed?`<span class="recommendation-installed" role="status">Installed</span><small>Ready to use in ${esc(agent)}</small>`:`<button class="button primary" data-review-recommendation="${i}" aria-label="Review & install ${esc(displaySkillName(r.name))}">Review & install</button><details class="action-menu recommendation-options"><summary aria-label="More options for ${esc(displaySkillName(r.name))}">More options</summary><div class="action-popover"><button data-save-recommendation="${i}">Save for later<small>Keep this suggestion without installing</small></button><button data-dismiss-recommendation="${i}">Not relevant</button></div></details>`}</div></article>`;
 }).join('')||'<div class="library-empty"><p>No suggestions left to review. Find saved suggestions above, or explore the collections.</p><button class="button" data-manage-tab="discover">Explore collections</button></div>'}</div>${coveredWorkspace()}`;
}
function renderManageWorkspace(){
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='manage'));
 document.querySelectorAll('[data-category]').forEach(b=>b.classList.remove('active'));
 $('#content').innerHTML=`<div class="page manage-page library-workspace">${libraryHeader()}${scopeBar()}<section class="library-body" aria-label="${manageTab==='for-you'?'Recommendations':manageTab==='discover'?'Discover skills':'Installed skills'}">${manageTab==='installed'?installedWorkspace():manageTab==='discover'?discoverWorkspace():recommendationsWorkspace()}</section></div>`;
 updateUsageSelection();if(typeof filterExcerpts==='function')filterExcerpts();
}
function updateUsageSelection(){const count=usageSample?.excerpts.filter(e=>e.selected&&e.text.trim()).length||0;const label=$('#usage-selected-count');if(label)label.textContent=count+' selected';const button=$('#run-recommendations');if(button)button.disabled=!count||!usageConfig.provider||!!activeJob||usageBusy;}
function showRecommendationResult(result){projectSelection=result.project?.id||'';if(result.target)projectAgent=result.target;usageConfig.provider=result.target;usageConfig.scope=result.scope||'all';recommendationResult=result;usageSample=null;modal.close();clearJobStatus();view='manage';manageTab='for-you';render();}
function openSkillDetails(id){const s=manageData.installed.find(s=>s.id===id);if(!s)return;showDialog(dialogHeader(esc(displaySkillName(s.name)))+`<p>${esc(s.description)}</p><p class="manage-note">${esc(s.name)} · ${esc(sourceLabel(s))} · ${(s.harnesses||[]).map(harnessLabel).join(' · ')}</p>${s.error?`<p class="form-error">${esc(s.error)}</p>`:''}<details><summary>Source and location</summary><p class="source-path">${esc(s.source)}</p><p class="source-path">${esc(s.location||'')}</p></details>${s.duplicates?.length?`<details><summary>Other copies available to the same agents · ${s.duplicates.length}</summary><p>Agent discovery rules decide which copy is used. Compare these locations before installing another copy.</p>${s.duplicates.map(d=>`<p class="source-path">${esc(d.location)} · ${d.agents.map(harnessLabel).join(', ')}</p>`).join('')}</details>`:''}<div class="manage-actions"><button class="button" data-duplicate-skill="${esc(s.id)}">Duplicate as new skill</button><button class="button" data-compare-copies="${esc(s.id)}">Compare copies</button><button class="button" data-multi-copy="${esc(s.id)}">Copy to agents</button></div>${s.readOnly?'<p class="manage-note">This copy is managed in another library. Remove it through its source agent.</p>':`<button class="button" data-remove="${esc(s.id)}">Remove and archive</button>`}`);}
async function selectManageTab(tab){manageTab=tab;activeCollection=null;renderManage();if(tab==='discover'&&!collectionData)await loadCollections();if(tab==='for-you'&&!usageInfo)await loadUsageInfo();}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');
 document.querySelectorAll('.action-menu[open]').forEach(menu=>{if(!menu.contains(e.target)||b)menu.open=false;});
 if(!b)return;
 try{
  if(b.dataset.manageTab){await selectManageTab(b.dataset.manageTab);}
  if(b.id==='onboard-project')projectForm();
  if(b.id==='manage-projects')projectList();
  if(b.id==='library-settings'){showDialog(dialogHeader('Library settings')+'<div id="provider-controls"></div><div class="manage-actions"><button class="button" id="agent-readiness-settings">Check agent readiness</button><button class="button" id="installation-history-settings">Installation history</button><button class="button" id="local-diagnostics">Local diagnostics</button><button class="button" id="library-health">Check library health</button></div>');renderProviderControls();}
  if(b.dataset.libraryDetail)openSkillDetails(b.dataset.libraryDetail);
  if(b.id==='show-removed')showDialog(dialogHeader('Removed skills')+`<p>Removed skills are archived here until you restore them.</p>${manageData.archived.map(s=>`<div class="archive-row"><span>${esc(displaySkillName(s.id))}<small>${esc(new Date(s.archived_at).toLocaleDateString())}</small></span><button class="button" data-restore="${esc(s.token)}">Restore</button></div>`).join('')||'<p class="manage-note">No removed skills.</p>'}`);
  if(b.id==='retry-collections')await loadCollections();
  if(b.id==='retry-usage-info')await loadUsageInfo();
  if(b.dataset.openCollection){activeCollection=b.dataset.openCollection;collectionSelection.clear();renderManage();}
  if(b.id==='back-collections'){activeCollection=null;renderManage();}
  if(b.id==='clear-collection-selection'){collectionSelection.clear();renderManage();}
  if(b.id==='select-collection-shown'){collectionData.find(c=>c.id===activeCollection).skills.filter(s=>!installedForTarget(s.name)&&[s.name,s.description].join(' ').toLowerCase().includes(query.toLowerCase().trim())).forEach(s=>collectionSelection.add(s.name));renderManage();}
  if(b.id==='review-collection-selection'){
   if(activeDraft||activeJob||(typeof multiCopy!=='undefined'&&multiCopy)||usageBusy||pendingWorkspaceRequests){toast('Finish or discard the current preview first.');return;}
   b.disabled=true;const names=collectionData.find(c=>c.id===activeCollection).skills.filter(s=>collectionSelection.has(s.name)&&!installedForTarget(s.name)).map(s=>s.name);
   previewPackage(await api('/api/collection-preview',{collection:activeCollection,names,target:collectionTarget}));
  }
  if(b.id==='preview-usage'){
   const revision=++usageRevision;usageBusy=true;usageError='';renderManage();
   try{const sample=await api('/api/usage-preview',{target:usageConfig.provider,days:usageConfig.days,project:projectSelection,scope:projectSelection?usageConfig.scope:'all'});if(revision!==usageRevision)return;usageSample=sample;if(typeof usageFilters!=='undefined')usageFilters={project:'',date:'',text:''};usageSample.excerpts.forEach(e=>e.selected=true);}catch(error){usageError=error.message;}finally{usageBusy=false;if(view==='manage'&&manageTab==='for-you')renderManage();}
  }
  if(b.id==='discard-usage'){usageRevision++;await api('/api/usage-discard',{});usageSample=null;renderManage();}
  if(b.id==='select-usage-all'||b.id==='select-usage-none'){usageSample.excerpts.forEach(e=>e.selected=b.id==='select-usage-all');renderManage();}
  if(b.id==='run-recommendations'){
   if(usageBusy)return;if(activeJob){showJobProgress();return;}if(activeDraft){toast('Install or discard the skill preview first.');return;}
   b.disabled=true;await startJob('recommend',{preview:usageSample.preview,provider:usageConfig.provider,excerpts:usageSample.excerpts.filter(e=>e.selected&&e.text.trim()).map(({id,text})=>({id,text}))});
  }
  if(b.id==='new-recommendations'){recommendationResult=null;usageSample=null;renderManage();if(!usageInfo)await loadUsageInfo();}
  if(b.dataset.reviewRecommendation!==undefined){
   const r=recommendationResult.recommendations[Number(b.dataset.reviewRecommendation)];
   if(activeDraft?.recommendationName===r.name&&!packageInstalling&&!pendingWorkspaceRequests){previewPackage(activeDraft);return;}
   if(activeDraft||activeJob||(typeof multiCopy!=='undefined'&&multiCopy)||usageBusy||pendingWorkspaceRequests){toast('Finish or discard the current preview first.');return;}
   b.disabled=true;b.textContent='Loading instructions…';
   try{
    const draft=await api('/api/collection-preview',{collection:r.collection,names:[r.name],target:recommendationResult.target,project:recommendationResult.project?.id||''});
    draft.firstSteps={[r.name]:r.firstStep};draft.recommendationName=r.name;previewPackage(draft);
   }finally{if(b.isConnected){b.disabled=false;b.textContent='Review & install';}}
  }
 }catch(error){errorMessage(error.message);}finally{if(b.isConnected&&['review-collection-selection','run-recommendations'].includes(b.id)){b.disabled=false;updateUsageSelection();}}
});
document.addEventListener('change',e=>{
 const el=e.target;
 if(el.id==='library-source'){librarySource=el.value;renderManage();}
 if(el.id==='project-scope'||el.id==='project-agent'){if(activeDraft||activeJob||(typeof multiCopy!=='undefined'&&multiCopy)||usageBusy||pendingWorkspaceRequests){toast('Finish the current preview or job before switching destinations.');renderManage();return;}clearJobStatus();lastJobRequest=null;usageRevision++;if(el.id==='project-scope'){projectSelection=el.value;usageConfig.scope='project';}else projectAgent=el.value;collectionTarget=projectSelection?projectAgent:'shared';usageConfig.provider=projectSelection?projectAgent:(usageInfo?.providers.find(p=>p.id===usageConfig.provider&&p.historyAnalysis)?.id||usageInfo?.providers.find(p=>p.installed&&p.historyAnalysis)?.id||'');usageSample=null;recommendationResult=null;collectionSelection.clear();renderManage();}
 if(el.id==='collection-target'){collectionTarget=el.value;renderManage();}
 if(el.dataset.collectionSkill){el.checked?collectionSelection.add(el.dataset.collectionSkill):collectionSelection.delete(el.dataset.collectionSkill);const count=collectionData.find(c=>c.id===activeCollection).skills.filter(s=>collectionSelection.has(s.name)&&!installedForTarget(s.name)).length;$('#collection-selection-count').textContent=count+' selected';$('#review-collection-selection').disabled=!count;}
 if(el.id==='usage-provider'){usageRevision++;usageConfig.provider=el.value;usageSample=null;usageError='';renderManage();}
 if(el.id==='usage-scope'){usageRevision++;usageConfig.scope=el.value;usageSample=null;usageError='';renderManage();}
 if(el.id==='usage-days'){usageRevision++;usageConfig.days=Number(el.value);usageSample=null;renderManage();}
 if(el.dataset.usageSelected){usageSample.excerpts.find(e=>e.id===el.dataset.usageSelected).selected=el.checked;updateUsageSelection();}
});
document.addEventListener('input',e=>{if(e.target.dataset.usageText){usageSample.excerpts.find(row=>row.id===e.target.dataset.usageText).text=e.target.value;updateUsageSelection();}});

function projectForm(){showDialog(dialogHeader('Bring a project into Skill-Desk')+`<p>Choose an existing local Git repository. Its skills stay with the project, separate from your personal libraries.</p><form id="project-form"><label for="project-name">Project name</label><input id="project-name" maxlength="80" placeholder="e.g. Customer portal"><label for="project-path">Local repository path</label><input id="project-path" required placeholder="/path/to/your/repository" autocomplete="off"><p class="manage-note">Use the repository root containing .git. Onboarding only remembers this location. Skill files are added after you review an installation.</p><p id="form-message" role="alert"></p><button class="button primary">Add project</button></form>`);}
function projectList(){showDialog(dialogHeader('Your projects')+`<p>Removing a project from this list leaves its repository and installed skills untouched.</p>${projectData.map(p=>`<article class="project-entry"><div><strong>${esc(p.name)}</strong><p class="source-path">${esc(p.path)}</p><small>${p.available?'Connected':'Unavailable. Restore this location or remove and onboard its new path.'}</small></div><button class="button" data-forget-project="${p.id}">Remove from list</button></article>`).join('')||'<p>No projects yet.</p>'}<button class="button primary" id="onboard-project">Add project</button><p id="form-message" role="alert"></p>`);}
document.addEventListener('submit',async e=>{if(e.target.id!=='project-form')return;e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const p=await api('/api/project-add',{name:$('#project-name').value,path:$('#project-path').value});projectSelection=p.id;usageConfig.scope='project';projectAgent='codex';collectionTarget='codex';usageConfig.provider='codex';usageSample=null;recommendationResult=null;await loadProjects();modal.close();await loadManage();renderManage();toast('Project added. Choose skills to install.');}catch(error){errorMessage(error.message);button.disabled=false;}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.forgetProject){await api('/api/project-remove',{id:b.dataset.forgetProject});await loadProjects();await loadManage();usageSample=null;recommendationResult=null;projectList();}if(b.dataset.copyStarter!==undefined){const r=recommendationResult.covered[Number(b.dataset.copyStarter)];await navigator.clipboard.writeText(r.firstStep);toast('First step copied');}}catch(error){errorMessage(error.message);}});
function coveredWorkspace(){const rows=recommendationResult?.covered||[];return rows.length?`<section class="covered-skills"><h3>Already covered by your library</h3><p>These are the agent’s comparisons of skill descriptions. Review the reasoning before relying on a match.</p>${rows.map((r,i)=>`<article><span class="recommendation-source">${esc(r.collectionName)} · ${esc(displaySkillName(r.name))}</span><h4>Already covered by ${esc(displaySkillName(r.installed))}</h4><p>${esc(r.reason)}</p><details><summary>Try your existing skill</summary><pre class="starter-prompt">${esc(r.firstStep)}</pre><button class="button" data-copy-starter="${i}">Copy first step</button></details></article>`).join('')}</section>`:'';}
function showFirstSteps(draft,names){const target=draft.target&&draft.target!=='shared'?draft.target:'codex';const agent=harnessLabel(target);const prefix=target==='opencode'?'Use the ':['claude','cursor'].includes(target)?'/':'$';const rows=names.map(name=>{return {name,prompt:draft.firstSteps?.[name]||`${prefix}${name}${target==='opencode'?' skill.':''} Help me apply this skill to one relevant task in my current project. Start by identifying a suitable task and proposing the first step.`};});showDialog(dialogHeader(draft.recommendationName?'Skill installed':'Put your new skills to work')+`<p>Open ${agent}${draft.project?' in '+esc(draft.project.name):' in your project'} and start a new session so it can discover the installed skills. Copy a starter below and adapt it to your task.</p>${rows.map((r,i)=>`<article class="first-step"><h3>${esc(displaySkillName(r.name))}</h3><pre class="starter-prompt">${esc(r.prompt)}</pre><button class="button" data-first-step="${i}">Copy first step</button></article>`).join('')}<p class="manage-note">These prompts are suggestions. Nothing runs until you send one to your agent.</p>`);document.querySelectorAll('[data-first-step]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(rows[Number(b.dataset.firstStep)].prompt);toast('First step copied');}catch(error){toast(error.message);}});}
loadProjects().catch(e=>toast(e.message));
