'use strict';
// Explicit review actions. Draft contents are never saved to browser storage.
let editorState=null,modelList=null,multiCopy=null,lastToolResult=null;
function draftKey(){return {draft:activeDraft.draft,candidate:selectedCandidate().candidate};}
function draftActions(){return `<div class="manage-actions"><button class="button" id="edit-draft">Edit instructions</button><button class="button" id="revise-draft">Revise with agent</button><button class="button" id="draft-revisions">Compare revision</button><button class="button" id="save-draft">Save draft locally</button><button class="button" id="maint-draft-tools">Files and revisions</button></div>`;}
function editorForm(){const s=selectedCandidate();editorState={...draftKey(),original:s.content};showDialog(dialogHeader('Edit draft instructions')+`<p>Edit the YAML name and description or the instructions. Nothing installs until you review the updated preview.</p><label for="draft-content">SKILL.md</label><textarea id="draft-content" rows="18" maxlength="200000" spellcheck="false">${esc(s.content)}</textarea><p id="draft-validation" role="status">Changes have not been validated.</p><details id="edit-diff" hidden><summary>Changes to this draft</summary><pre class="skill-preview"></pre></details><div class="manage-actions"><button class="button" id="validate-draft">Validate and compare</button><button class="button primary" id="apply-draft" disabled>Apply to preview</button><button class="button" id="draft-back">Back to preview</button></div><p id="form-message" role="alert"></p>`);}
function revisionForm(){showDialog(dialogHeader('Revise this draft')+`<p>The selected agent receives these instructions and your request. A successful revision creates a new preview; the previous draft remains available.</p><label for="revision-request">What should change?</label><textarea id="revision-request" rows="5" maxlength="10000"></textarea><button class="button primary" id="run-revision">Generate revision</button><button class="button" id="draft-back">Back to preview</button><p id="form-message" role="alert"></p>`);}
async function savedDraftsDialog(){const data=await api('/api/saved-drafts',{});showDialog(dialogHeader('Saved drafts')+`<p>These drafts were explicitly saved on this machine. Reopening checks that their destination is still available.</p>${data.previews.length?'<h3>Unsaved previews in this session</h3>':''}${data.previews.map(d=>`<article class="readiness-entry"><p>${esc(d.candidates.map(c=>c.name).join(', '))}</p><p class="source-path">${esc(d.destination)}</p><button class="button" data-resume-draft="${d.draft}">Review preview</button><button class="text-link" data-discard-preview="${d.draft}">Discard preview</button></article>`).join('')}<h3>Saved on this machine</h3>${data.drafts.map(d=>`<article class="readiness-entry"><h3>${esc(d.name)}${d.template?' · Template':''}</h3><p>${esc(new Date(d.savedAt*1000).toLocaleString())}</p><p class="source-path">${esc(d.destination)}</p><button class="button" data-open-draft="${d.id}">Reopen</button><button class="text-link" data-delete-draft="${d.id}">Delete saved draft</button></article>`).join('')||'<p>No saved drafts.</p>'}<p id="form-message" role="alert"></p>`);}
function showModels(data){modelList=data;showDialog(dialogHeader('OpenCode models')+`<p>${esc(data.pricing)}</p>${data.message?`<p role="status">${esc(data.message)}</p>`:''}<label for="model-search">Find a model</label><input type="search" id="model-search" autocomplete="off"><div id="model-results"></div><p>Manual model entry remains available in Library settings.</p>`);paintModels('');}
function paintModels(query){const rows=(modelList?.models||[]).filter(m=>m.id.toLowerCase().includes(query.toLowerCase()));$('#model-results').innerHTML=rows.slice(0,100).map(m=>`<button class="button model-option" data-model-id="${esc(m.id)}">${esc(m.id)}${m.free===true?' · Free according to CLI metadata':''}</button>`).join('')||'<p>No matching models.</p>';}
function showHealth(data){showDialog(dialogHeader('Library health')+`<p>${data.checked} skill folders checked. ${data.partial?'The report reached its scan limit.':''} No files were changed.</p>${data.issues.map(i=>`<article class="readiness-entry"><h3>${esc(i.name)}</h3><p>${esc(i.message)}</p><p class="source-path">${esc(i.location)}</p></article>`).join('')||'<p>No metadata or local-reference problems found.</p>'}`);}
function specialJob(job){return ['provider-models','provider-test','library-health','usage-deep-preview','workbench'].includes(job.action);}
function showToolResult(job){lastToolResult=job;clearJobStatus();if(job.result.workbenchResult){showMaintenanceResult(job.result);return;}if(job.result.modelList)showModels(job.result.modelList);else if(job.result.libraryHealth)showHealth(job.result.libraryHealth);else if(job.result.connectionTest){const r=job.result.connectionTest;showDialog(dialogHeader('Connection test passed')+`<p>${esc(harnessLabel(r.provider))} returned the expected structured response using ${esc(r.model||'its configured default model')}.</p><p>Tested ${esc(new Date(r.checkedAt*1000).toLocaleString())}. This checks a small synthetic request, not future availability.</p>`);loadProviders();}else{usageSample=job.result;usageSample.excerpts.forEach(e=>e.selected=true);usageFilters={project:'',date:'',text:''};modal.close();view='manage';manageTab='for-you';renderManage();}}
function duplicateForm(id){const s=manageData.installed.find(s=>s.id===id);showDialog(dialogHeader('Duplicate as a new skill')+`<p>Supporting files are preserved. Review any instructions that still mention the original name.</p><label for="duplicate-name">New skill name</label><input id="duplicate-name" maxlength="63" value="${esc(s.name.slice(0,54)+'-copy')}"><label for="duplicate-target">Destination agent</label><select id="duplicate-target">${agentOptions(projectSelection?projectAgent:'codex')}</select><p>${esc(selectedProject()?.name||'Personal library')}</p><button class="button primary" id="prepare-duplicate" data-source="${esc(id)}">Review duplicate</button><p id="form-message" role="alert"></p>`);}
function multiCopyForm(id){showDialog(dialogHeader('Copy to agents')+`<p>Choose destinations in ${esc(selectedProject()?.name||'your personal libraries')}. Each copy is independent. You will review conflicts before installing.</p>${Object.entries(agentLabels).map(([key,name])=>`<label class="checkbox-label"><input type="checkbox" data-copy-agent="${key}">${esc(name)}</label>`).join('')}<button class="button primary" id="prepare-multi-copy" data-source="${esc(id)}">Review destinations</button><p id="form-message" role="alert"></p>`);}
function paintMultiCopy(){showDialog(dialogHeader('Review copies')+`<p>The complete source folder will be copied. Existing destinations are skipped.</p>${multiCopy.previews.map((p,i)=>`<article class="readiness-entry"><h3>${esc(harnessLabel(p.target))}</h3><p class="source-path">${esc(p.destination)}</p><p>${esc(p.candidates[0].name)} · ${p.candidates[0].files.length} files</p><pre class="skill-preview">${esc(p.candidates[0].content)}</pre>${(p.candidates[0].compatibility?.issues||[]).map(x=>`<p class="manage-note">${esc(x.message)}</p>`).join('')}${p.done?'<p>Installed</p>':p.candidates[0].conflict?`<p class="form-error">${esc(p.candidates[0].conflict)}</p>`:`<label class="checkbox-label"><input type="checkbox" data-copy-selection="${i}" ${p.selected!==false?'checked':''}>Install this copy</label>`}${p.error?`<p class="form-error">${esc(p.error)}</p>`:''}</article>`).join('')}<button class="button primary" id="install-multi-copy" ${multiCopy.previews.some(p=>!p.done&&!p.candidates[0].conflict&&p.selected!==false)?'':'disabled'}>Install selected copies</button><button class="button" id="discard-multi-copy">Close and discard previews</button><p id="form-message" role="alert"></p>`);}
async function compareCopies(id){const source=manageData.installed.find(s=>s.id===id);const rows=manageData.installed.filter(s=>s.id!==id&&s.name.toLowerCase()===source.name.toLowerCase());showDialog(dialogHeader('Compare installed copies')+`<p class="source-path">${esc(source.location)}</p>${rows.length?`<label for="compare-copy">Compare with</label><select id="compare-copy">${rows.map(r=>`<option value="${esc(r.id)}">${esc(r.location)}</option>`).join('')}</select><button class="button" id="run-copy-comparison">Compare contents</button>`:'<p>No separate copies with this name were found.</p>'}<div id="copy-comparison-result"></div><p id="form-message" role="alert"></p>`);if(rows.length)$('#run-copy-comparison').onclick=async()=>{try{const data=await api('/api/copy-comparison',{left:id,right:$('#compare-copy').value});$('#copy-comparison-result').innerHTML=`<p role="status">${data.identical?'These copies are identical.':'These copies have diverged.'}</p>${['added','removed','changed'].map(k=>`<p>${k}: ${data[k].map(esc).join(', ')||'none'}</p>`).join('')}<pre class="skill-preview">${esc(data.diff||'No instruction changes.')}</pre>${(data.fileChanges||[]).filter(x=>x.file!=='SKILL.md').map(x=>`<details><summary>${esc(x.file)}</summary><pre class="skill-preview">${esc(x.diff)}</pre></details>`).join('')}${data.truncated?'<p>Diff display truncated at 100 KB.</p>':''}`;}catch(e){errorMessage(e.message);}};}
function requireIdle(){if(activeJob||activeDraft||multiCopy||pendingWorkspaceRequests){toast('Finish the current job or preview first.');return false;}return true;}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.id==='resume-multi-copy')paintMultiCopy();
 if(b.id==='edit-draft')editorForm();
 if(b.id==='revise-draft')revisionForm();
 if(b.id==='draft-back')previewDraft(activeDraft);
 if(b.id==='validate-draft'){const content=$('#draft-content').value;const result=await api('/api/draft-validate',{...editorState,content});if(!$('#draft-content')||$('#draft-content').value!==content)return;if(!result.valid){$('#draft-validation').textContent=result.message;errorMessage(result.message);$('#apply-draft').disabled=true;return;}$('#form-message').textContent='';$('#draft-validation').textContent='Valid metadata and references: '+result.name;$('#apply-draft').disabled=false;$('#edit-diff').hidden=false;$('#edit-diff pre').textContent=result.diff||'No changes.';}
 if(b.id==='apply-draft'){b.disabled=true;const next=await api('/api/draft-edit',{...editorState,content:$('#draft-content').value});previewDraft(next);}
 if(b.id==='save-draft'){b.disabled=true;await api('/api/draft-save',draftKey());toast('Draft saved on this machine');b.textContent='Saved locally';}
 if(b.id==='draft-revisions'){const r=await api('/api/draft-revision',draftKey());showDialog(dialogHeader('Draft revision')+`<pre class="skill-preview">${esc(r.diff||'No previous revision for this draft.')}</pre><button class="button" id="draft-back">Back to preview</button>`);}
 if(b.dataset.draftFile){const r=await api('/api/draft-file',{...draftKey(),file:b.dataset.draftFile});showDialog(dialogHeader(esc(r.file))+`<pre class="skill-preview">${esc(r.previewable?r.content:r.message)}</pre><button class="button" id="draft-back">Back to preview</button>`);}
 if(b.id==='run-revision'){b.disabled=true;await startJob('draft-revise',{...draftKey(),instruction:$('#revision-request').value});}
 if(b.id==='saved-drafts'){if(activeJob||multiCopy){toast('Finish the running job or copy review first.');return;}await savedDraftsDialog();}
 if(b.dataset.resumeDraft)previewDraft(await api('/api/draft-resume',{draft:b.dataset.resumeDraft}));
 if(b.dataset.discardPreview){await api('/api/discard',{draft:b.dataset.discardPreview});if(activeDraft?.draft===b.dataset.discardPreview){activeDraft=null;clearJobStatus();}await savedDraftsDialog();}
 if(b.dataset.openDraft){b.disabled=true;previewDraft(await api('/api/draft-reopen',{id:b.dataset.openDraft}));}
 if(b.dataset.deleteDraft){const id=b.dataset.deleteDraft;showDialog(dialogHeader('Delete saved draft?')+'<p>This deletes only the saved draft. Installed skills are preserved.</p><button class="button" id="confirm-delete-draft">Delete draft</button><p id="form-message" role="alert"></p>');$('#confirm-delete-draft').onclick=async()=>{try{await api('/api/draft-delete',{id});await savedDraftsDialog();}catch(e){errorMessage(e.message);}};}
 if(b.id==='list-opencode-models'){if(!requireIdle())return;await startJob('provider-models',{});}
 if(b.id==='test-provider'){if(!requireIdle())return;const provider=providerData.selected,model=$('#author-model')?.value||providerData.models?.[provider]||'';showDialog(dialogHeader('Test model connection')+`<p>This sends one synthetic prompt asking for {"ok":true} through ${esc(harnessLabel(provider))}, using ${esc(model||'its configured default model')}. It uses that model’s normal allowance or pricing.</p><button class="button primary" id="confirm-provider-test">Send test prompt</button><p id="form-message" role="alert"></p>`);$('#confirm-provider-test').onclick=()=>startJob('provider-test',{provider,model});}
 if(b.dataset.modelId){await api('/api/provider',{provider:'opencode',model:b.dataset.modelId});await loadProviders();modal.close();toast('OpenCode model selected');}
 if(b.id==='library-health'){if(!requireIdle())return;await startJob('library-health',{});}
 if(b.dataset.duplicateSkill){if(!requireIdle())return;duplicateForm(b.dataset.duplicateSkill);}
 if(b.id==='prepare-duplicate'){b.disabled=true;previewDraft(await api('/api/duplicate-preview',{id:b.dataset.source,name:$('#duplicate-name').value,target:$('#duplicate-target').value,project:projectSelection}));}
 if(b.dataset.compareCopies)await compareCopies(b.dataset.compareCopies);
 if(b.dataset.multiCopy){if(!requireIdle())return;multiCopyForm(b.dataset.multiCopy);}
 if(b.id==='prepare-multi-copy'){b.disabled=true;multiCopy=await api('/api/multi-copy-preview',{id:b.dataset.source,targets:[...modal.querySelectorAll('[data-copy-agent]:checked')].map(x=>x.dataset.copyAgent),project:projectSelection});paintMultiCopy();}
 if(b.id==='install-multi-copy'){b.disabled=true;packageInstalling=true;try{for(const p of multiCopy.previews){if(p.done||p.selected===false||p.candidates[0].conflict)continue;try{await api('/api/install',{draft:p.draft,candidate:p.candidates[0].candidate,reviewDigest:p.candidates[0].treeDigest});p.done=true;delete p.error;}catch(e){p.error=e.message;}}await loadManage();await syncCatalog();paintMultiCopy();}finally{packageInstalling=false;}}
 if(b.id==='discard-multi-copy'){for(const p of multiCopy.previews)await api('/api/discard',{draft:p.draft});multiCopy=null;modal.close();}
 if(b.id==='preview-deeper'){if(!requireIdle())return;usageSample=null;await startJob('usage-deep-preview',{target:usageConfig.provider,days:usageConfig.days,project:projectSelection,scope:projectSelection?usageConfig.scope:'all'});}
 }catch(error){errorMessage(error.message);if(b.isConnected)b.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='draft-content'){$('#apply-draft').disabled=true;$('#draft-validation').textContent='Changes have not been validated.';}if(e.target.id==='model-search')paintModels(e.target.value);if(e.target.id==='usage-filter-text'){usageFilters.text=e.target.value;filterExcerpts();}});
document.addEventListener('change',e=>{if(e.target.dataset.copySelection!==undefined){multiCopy.previews[Number(e.target.dataset.copySelection)].selected=e.target.checked;$('#install-multi-copy').disabled=!multiCopy.previews.some(p=>!p.done&&!p.candidates[0].conflict&&p.selected!==false);}if(e.target.id==='usage-filter-project'||e.target.id==='usage-filter-date'){usageFilters[e.target.id==='usage-filter-project'?'project':'date']=e.target.value;filterExcerpts();}});
let usageFilters={project:'',date:'',text:''};
function excerptFilters(){return `<div class="excerpt-filters"><label>Project<select id="usage-filter-project"><option value="">All sampled projects</option>${[...new Set(usageSample.excerpts.map(e=>e.project||'Project unknown'))].sort().map(p=>`<option ${usageFilters.project===p?'selected':''}>${esc(p)}</option>`).join('')}</select></label><label>Date<select id="usage-filter-date"><option value="">All sampled dates</option>${[...new Set(usageSample.excerpts.map(e=>e.date))].sort().reverse().map(d=>`<option ${usageFilters.date===d?'selected':''}>${esc(d)}</option>`).join('')}</select></label><label>Find text<input id="usage-filter-text" type="search" value="${esc(usageFilters.text)}"></label></div><p id="filter-count" role="status"></p><p class="manage-note">Filters only change what is visible. Selected hidden excerpts remain selected for analysis.</p>`;}
function filterExcerpts(){if(!usageSample)return;let shown=0;document.querySelectorAll('.usage-excerpts article').forEach(article=>{const id=article.querySelector('[data-usage-text]')?.dataset.usageText;const e=usageSample.excerpts.find(e=>e.id===id);const visible=e&&(!usageFilters.project||(e.project||'Project unknown')===usageFilters.project)&&(!usageFilters.date||e.date===usageFilters.date)&&e.text.toLowerCase().includes(usageFilters.text.toLowerCase());article.hidden=!visible;if(visible)shown++;});if($('#filter-count'))$('#filter-count').textContent=shown+' of '+usageSample.excerpts.length+' excerpts visible';}
